from sqlalchemy import Column, String, Integer, ForeignKey, DateTime, Float
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.sql import func
import uuid
from database import Base
from app.models.core import SoftDeleteMixin

def generate_uuid():
    return str(uuid.uuid4())

class AIGeneratedAssessment(Base, SoftDeleteMixin):
    """
    Tracks assessment drafts generated by AI for Faculty.
    """
    __tablename__ = "ai_generated_assessments"
    id = Column(String, primary_key=True, index=True, default=generate_uuid)
    college_id = Column(String, ForeignKey("colleges.id", ondelete="CASCADE"), nullable=False, index=True)
    faculty_id = Column(String, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    course_id = Column(String, ForeignKey("courses.id", ondelete="CASCADE"), nullable=False)
    type = Column(String, nullable=False)  # quiz, assignment
    title = Column(String, nullable=False)
    prompt_used = Column(String, nullable=True)
    status = Column(String, nullable=False, default="draft")  # draft, published
    created_at = Column(DateTime(timezone=True), server_default=func.now())

class AssessmentQuestion(Base, SoftDeleteMixin):
    """
    Individual generated question tied to an assessment, mapped cleanly to outcomes.
    """
    __tablename__ = "assessment_questions"
    id = Column(String, primary_key=True, index=True, default=generate_uuid)
    college_id = Column(String, ForeignKey("colleges.id", ondelete="CASCADE"), nullable=False, index=True)
    assessment_id = Column(String, ForeignKey("ai_generated_assessments.id", ondelete="CASCADE"), nullable=False)
    
    question_text = Column(String, nullable=False)
    question_type = Column(String, nullable=False)  # MCQ, short, long
    marks = Column(Float, nullable=False, default=1.0)
    
    # Strictly bound structural metadata
    co_id = Column(String, ForeignKey("course_outcomes.id", ondelete="SET NULL"), nullable=True)
    po_id = Column(String, ForeignKey("program_outcomes.id", ondelete="SET NULL"), nullable=True)
    bloom_level = Column(String, nullable=True)
    
    # Content structure
    options = Column(JSONB, nullable=True)  # For MCQs
    answer_key = Column(String, nullable=True)
    
    created_at = Column(DateTime(timezone=True), server_default=func.now())
