import React, { useState, useEffect } from 'react';
import { toast } from 'sonner';
import api, { facultyAPI, hodAssignmentsAPI } from '../../services/api';
import AssignmentCardGrid from './AssignmentCardGrid';


const HODClassInChargeTab = () => {
  const [sections, setSections] = useState([]);
  const [assignedItems, setAssignedItems] = useState([]);
  const [faculty, setFaculty] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchData();
  }, []);

  const fetchData = async () => {
    try {
      setLoading(true);
      const [secRes, facRes, assignRes] = await Promise.all([
        api.get('/api/sections'), // Get sections logic from server
        facultyAPI.teachers(),
        hodAssignmentsAPI.getClassInCharges()
      ]);
      
      // The API returns sections, we need to map them such that they have title and subtitles.
      // Usually a Section model has department_id, batch, name (section). 
      // We map it to { id, batch, section, department, name: "Section A", id: "CSE 2022-26" }
      const formattedSections = secRes.data.map(s => ({
        id: s.id,
        department: s.department_id,
        batch: s.batch,
        section: s.name,
        semester: s.current_semester || 1,
        // UI fields
        title: `${s.batch} - ${s.name}`,
        subtitle: `Dept: ${s.department_id} | Sem: ${s.current_semester || 1}`
      }));
      
      setSections(formattedSections);
      setFaculty(facRes.data);
      setAssignedItems(assignRes.data);
    } catch (err) {
      toast.error('Failed to load class in-charge data');
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const handleAssign = async (sectionItem, facultyId) => {
    try {
      await hodAssignmentsAPI.createClassInCharge({
        faculty_ids: [facultyId],
        department: sectionItem.department,
        batch: sectionItem.batch,
        section: sectionItem.section,
        semester: sectionItem.semester
      });
      toast.success('Assigned successfully');
      fetchData(); // Refresh since ID is generated by backend
    } catch (err) {
      toast.error('Failed to assign faculty');
    }
  };

  const handleRemove = async (assignmentId) => {
    try {
      await hodAssignmentsAPI.deleteClassInCharge(assignmentId);
      toast.success('Assignment removed');
      fetchData();
    } catch (err) {
      toast.error('Failed to remove assignment');
    }
  };

  const completionFn = (item, assignments) => {
    const count = assignments.length;
    const target = 1; // Assuming target is at least 1 class in-charge per section
    return {
      count,
      target
    };
  };

  if (loading) {
     return <div className="p-8 text-center text-gray-500 dark:text-gray-400 animate-pulse">Loading assignments...</div>;
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-xl font-bold text-gray-900 dark:text-white">Class In-Charges</h2>
          <p className="text-sm text-gray-500 dark:text-gray-400 mt-1">
            Assign multiple faculty members to oversee a specific class section.
          </p>
        </div>
      </div>

      <AssignmentCardGrid
        items={sections}
        assignedItems={assignedItems}
        facultyList={faculty}
        onAssign={handleAssign}
        onRemove={handleRemove}
        pickerType="multi"
        completionFn={completionFn}
        titleKey="title"
        subtitleKey="subtitle"
        itemMatchKey="section" // Using our custom section matcher
      />
    </div>
  );
};

export default HODClassInChargeTab;
