// ── AcadMix PCB Studio — Component Catalog ───────────────────────────────────
// The full catalog of available PCB components for the library panel.

import type { CatalogEntry, ComponentCategory, ComponentType } from './types';

function createPins(count: number, side: 'left' | 'right' | 'top' | 'bottom', startIndex: number = 1, prefix: string = '') {
  return Array.from({ length: count }, (_, i) => ({
    id: `${prefix}${startIndex + i}`,
    label: `${prefix}${startIndex + i}`,
    type: 'bidirectional' as const,
    side,
  }));
}

export const COMPONENT_CATALOG: CatalogEntry[] = [
  // ── Passive Components ─────────────────────────────────────────────────────
  { type: 'resistor', label: 'Resistor (0805)', category: 'passive', description: 'SMD Resistor', refDesPrefix: 'R',
    defaultProperties: { value: '10kΩ', package: '0805', tolerance: '5%' },
    pins: [{ id: '1', label: '1', type: 'bidirectional', side: 'left' }, { id: '2', label: '2', type: 'bidirectional', side: 'right' }] },
  { type: 'resistor_th', label: 'Resistor (TH)', category: 'passive', description: 'Through-hole Resistor', refDesPrefix: 'R',
    defaultProperties: { value: '330Ω', package: 'TH 1/4W' },
    pins: [{ id: '1', label: '1', type: 'bidirectional', side: 'left' }, { id: '2', label: '2', type: 'bidirectional', side: 'right' }] },
  { type: 'capacitor', label: 'Capacitor (0805)', category: 'passive', description: 'SMD Ceramic Capacitor', refDesPrefix: 'C',
    defaultProperties: { value: '100nF', package: '0805' },
    pins: [{ id: '1', label: '1', type: 'bidirectional', side: 'left' }, { id: '2', label: '2', type: 'bidirectional', side: 'right' }] },
  { type: 'capacitor_elec', label: 'Electrolytic Cap', category: 'passive', description: 'Electrolytic Capacitor', refDesPrefix: 'C',
    defaultProperties: { value: '10uF', package: 'SMD-D', voltage: '16V' },
    pins: [{ id: 'plus', label: '+', type: 'bidirectional', side: 'left' }, { id: 'minus', label: '-', type: 'bidirectional', side: 'right' }] },
  { type: 'inductor', label: 'Inductor (SMD)', category: 'passive', description: 'Power Inductor', refDesPrefix: 'L',
    defaultProperties: { value: '10µH', package: '12x12mm' },
    pins: [{ id: '1', label: '1', type: 'bidirectional', side: 'left' }, { id: '2', label: '2', type: 'bidirectional', side: 'right' }] },
  { type: 'diode', label: 'Diode (SMA)', category: 'passive', description: 'Standard/Schottky Diode', refDesPrefix: 'D',
    defaultProperties: { value: '1N4148', package: 'SOD-323' },
    pins: [{ id: 'anode', label: 'A', type: 'bidirectional', side: 'left' }, { id: 'cathode', label: 'K', type: 'bidirectional', side: 'right' }] },
  { type: 'led', label: 'LED (0805)', category: 'passive', description: 'Light Emitting Diode', refDesPrefix: 'D',
    defaultProperties: { value: 'Red', color: 'red', package: '0805' },
    pins: [{ id: 'anode', label: 'A', type: 'bidirectional', side: 'left' }, { id: 'cathode', label: 'K', type: 'bidirectional', side: 'right' }] },
  { type: 'crystal', label: 'Crystal Osc.', category: 'passive', description: 'SMD/TH Crystal', refDesPrefix: 'Y',
    defaultProperties: { value: '16MHz', package: 'HC-49' },
    pins: [{ id: '1', label: '1', type: 'bidirectional', side: 'left' }, { id: '2', label: '2', type: 'bidirectional', side: 'right' }] },
  { type: 'potentiometer', label: 'Potentiometer', category: 'passive', description: 'Trimpot / Rotary Pot', refDesPrefix: 'RV',
    defaultProperties: { value: '10kΩ', package: 'Through-hole' },
    pins: [{ id: '1', label: '1', type: 'bidirectional', side: 'left' }, { id: '2', label: 'Wiper', type: 'bidirectional', side: 'top' }, { id: '3', label: '3', type: 'bidirectional', side: 'right' }] },
  { type: 'varistor', label: 'Varistor (MOV)', category: 'passive', description: 'Metal Oxide Varistor', refDesPrefix: 'RV',
    defaultProperties: { value: '14D471K', package: 'Disc' },
    pins: [{ id: '1', label: '1', type: 'bidirectional', side: 'left' }, { id: '2', label: '2', type: 'bidirectional', side: 'right' }] },
  { type: 'photoresistor', label: 'Photoresistor', category: 'passive', description: 'LDR Sensor', refDesPrefix: 'R',
    defaultProperties: { value: 'GL5528', package: 'THT' },
    pins: [{ id: '1', label: '1', type: 'bidirectional', side: 'left' }, { id: '2', label: '2', type: 'bidirectional', side: 'right' }] },
  { type: 'thermistor', label: 'Thermistor (NTC)', category: 'passive', description: 'Temperature dependent resistor', refDesPrefix: 'TH',
    defaultProperties: { value: '10kΩ', package: 'THT' },
    pins: [{ id: '1', label: '1', type: 'bidirectional', side: 'left' }, { id: '2', label: '2', type: 'bidirectional', side: 'right' }] },
  { type: 'zener', label: 'Zener Diode', category: 'passive', description: 'Voltage Reference Diode', refDesPrefix: 'D',
    defaultProperties: { value: '3.3V', package: 'SOD-123' },
    pins: [{ id: 'anode', label: 'A', type: 'bidirectional', side: 'left' }, { id: 'cathode', label: 'K', type: 'bidirectional', side: 'right' }] },
  { type: 'schottky', label: 'Schottky Diode', category: 'passive', description: 'Low Vf Diode', refDesPrefix: 'D',
    defaultProperties: { value: '1N5819', package: 'DO-41' },
    pins: [{ id: 'anode', label: 'A', type: 'bidirectional', side: 'left' }, { id: 'cathode', label: 'K', type: 'bidirectional', side: 'right' }] },
  { type: 'fuse', label: 'PTC Resettable Fuse', category: 'passive', description: 'Overcurrent protection', refDesPrefix: 'F',
    defaultProperties: { value: '500mA', package: '1206' },
    pins: [{ id: '1', label: '1', type: 'bidirectional', side: 'left' }, { id: '2', label: '2', type: 'bidirectional', side: 'right' }] },
  { type: 'via', label: 'Via (Layer Jump)', category: 'passive', description: 'Connects Top and Bottom layers', refDesPrefix: 'V',
    defaultProperties: { drill: '0.3mm', pad: '0.6mm' },
    pins: [{ id: 'top', label: 'T', type: 'bidirectional', side: 'top' }, { id: 'bot', label: 'B', type: 'bidirectional', side: 'bottom' }] },

  // ── Active Semiconductors ──────────────────────────────────────────────────
  { type: 'npn', label: 'NPN Transistor', category: 'active', description: 'NPN BJT', refDesPrefix: 'Q',
    defaultProperties: { value: '2N3904', package: 'SOT-23' },
    pins: [{ id: 'base', label: 'B', type: 'input', side: 'left' }, { id: 'collector', label: 'C', type: 'output', side: 'top' }, { id: 'emitter', label: 'E', type: 'output', side: 'bottom' }] },
  { type: 'pnp', label: 'PNP Transistor', category: 'active', description: 'PNP BJT', refDesPrefix: 'Q',
    defaultProperties: { value: '2N3906', package: 'SOT-23' },
    pins: [{ id: 'base', label: 'B', type: 'input', side: 'left' }, { id: 'collector', label: 'C', type: 'output', side: 'top' }, { id: 'emitter', label: 'E', type: 'output', side: 'bottom' }] },
  { type: 'nmosfet', label: 'N-Channel MOSFET', category: 'active', description: 'N-MOSFET', refDesPrefix: 'Q',
    defaultProperties: { value: 'IRLZ44N', package: 'TO-220' },
    pins: [{ id: 'gate', label: 'G', type: 'input', side: 'left' }, { id: 'drain', label: 'D', type: 'output', side: 'top' }, { id: 'source', label: 'S', type: 'output', side: 'bottom' }] },
  { type: 'opamp', label: 'Op-Amp (Single)', category: 'active', description: 'Operational Amplifier', refDesPrefix: 'U',
    defaultProperties: { value: 'LM358', package: 'SOIC-8' },
    pins: [{ id: 'vplus', label: 'V+', type: 'input', side: 'left' }, { id: 'vminus', label: 'V−', type: 'input', side: 'left' }, { id: 'out', label: 'OUT', type: 'output', side: 'right' }, { id: 'vcc', label: 'VCC', type: 'power', side: 'top' }, { id: 'vee', label: 'VEE', type: 'power', side: 'bottom' }] },
  { type: 'voltageRegulator', label: 'LDO Regulator', category: 'active', description: 'AMS1117 / LM7805', refDesPrefix: 'U',
    defaultProperties: { value: 'AMS1117-3.3', package: 'SOT-223' },
    pins: [{ id: 'vin', label: 'IN', type: 'input', side: 'left' }, { id: 'vout', label: 'OUT', type: 'output', side: 'right' }, { id: 'gnd', label: 'GND', type: 'ground', side: 'bottom' }] },
  { type: 'lm317', label: 'LM317 Adj Reg', category: 'active', description: 'Adjustable Voltage Regulator', refDesPrefix: 'U',
    defaultProperties: { value: 'LM317T', package: 'TO-220' },
    pins: [{ id: 'adj', label: 'ADJ', type: 'input', side: 'left' }, { id: 'vout', label: 'OUT', type: 'output', side: 'right' }, { id: 'vin', label: 'IN', type: 'power', side: 'top' }] },
  { type: 'pmosfet', label: 'P-Channel MOSFET', category: 'active', description: 'P-MOSFET', refDesPrefix: 'Q',
    defaultProperties: { value: 'IRF9540N', package: 'TO-220' },
    pins: [{ id: 'gate', label: 'G', type: 'input', side: 'left' }, { id: 'drain', label: 'D', type: 'output', side: 'bottom' }, { id: 'source', label: 'S', type: 'power', side: 'top' }] },
  { type: 'darlington', label: 'Darlington Transistor', category: 'active', description: 'High gain NPN Darlington', refDesPrefix: 'Q',
    defaultProperties: { value: 'TIP120', package: 'TO-220' },
    pins: [{ id: 'base', label: 'B', type: 'input', side: 'left' }, { id: 'collector', label: 'C', type: 'output', side: 'top' }, { id: 'emitter', label: 'E', type: 'ground', side: 'bottom' }] },
  { type: 'triac', label: 'TRIAC', category: 'active', description: 'AC Switch', refDesPrefix: 'Q',
    defaultProperties: { value: 'BTA16', package: 'TO-220' },
    pins: [{ id: 'mt1', label: 'A1', type: 'bidirectional', side: 'bottom' }, { id: 'mt2', label: 'A2', type: 'bidirectional', side: 'top' }, { id: 'gate', label: 'G', type: 'input', side: 'left' }] },

  // ── ICs & Digital ──────────────────────────────────────────────────────────
  { type: 'timer555', label: 'NE555 Timer', category: 'ic', description: 'Timer IC', refDesPrefix: 'U',
    defaultProperties: { value: 'NE555', package: 'SOIC-8' },
    pins: [ ...createPins(4, 'left', 1), ...createPins(4, 'right', 5) ] },
  { type: 'atmega328', label: 'ATmega328P', category: 'ic', description: 'AVR Microcontroller', refDesPrefix: 'U',
    defaultProperties: { value: 'ATmega328P-AU', package: 'TQFP-32' },
    pins: [ ...createPins(8, 'left', 1), ...createPins(8, 'bottom', 9), ...createPins(8, 'right', 17), ...createPins(8, 'top', 25) ] },
  { type: 'esp32', label: 'ESP32-WROOM', category: 'ic', description: 'Wi-Fi/Bluetooth MCU Module', refDesPrefix: 'U',
    defaultProperties: { value: 'ESP32-WROOM-32D', package: 'Module' },
    pins: [ ...createPins(14, 'left', 1), ...createPins(14, 'right', 15), ...createPins(10, 'bottom', 29) ] },
  { type: 'l298n', label: 'L298N Motor Driver', category: 'ic', description: 'Dual H-Bridge Driver', refDesPrefix: 'U',
    defaultProperties: { value: 'L298N', package: 'Multiwatt-15' },
    pins: [ ...createPins(7, 'left', 1), ...createPins(8, 'right', 8) ] },
  { type: 'logicGate', label: '74HC Series Logic', category: 'ic', description: 'Generic Logic IC', refDesPrefix: 'U',
    defaultProperties: { value: '74HC08', package: 'SOIC-14' },
    pins: [ ...createPins(7, 'left', 1), ...createPins(7, 'right', 8) ] },
  { type: 'icChip', label: 'Generic IC (DIP-8)', category: 'ic', description: 'Generic 8-pin IC', refDesPrefix: 'U',
    defaultProperties: { value: 'IC', package: 'DIP-8' },
    pins: [ ...createPins(4, 'left', 1), ...createPins(4, 'right', 5) ] },
  { type: 'stm32', label: 'STM32F103C8T6', category: 'ic', description: 'ARM Cortex-M3 MCU', refDesPrefix: 'U',
    defaultProperties: { value: 'STM32F103C8T6', package: 'LQFP-48' },
    pins: [ ...createPins(12, 'left', 1), ...createPins(12, 'bottom', 13), ...createPins(12, 'right', 25), ...createPins(12, 'top', 37) ] },
  { type: 'pic16f', label: 'PIC16F877A', category: 'ic', description: '8-bit PIC Microcontroller', refDesPrefix: 'U',
    defaultProperties: { value: 'PIC16F877A', package: 'DIP-40' },
    pins: [ ...createPins(20, 'left', 1), ...createPins(20, 'right', 21) ] },
  { type: 'shiftreg', label: '74HC595', category: 'ic', description: '8-bit Shift Register', refDesPrefix: 'U',
    defaultProperties: { value: '74HC595', package: 'DIP-16' },
    pins: [ ...createPins(8, 'left', 1), ...createPins(8, 'right', 9) ] },
  { type: 'l293d', label: 'L293D', category: 'ic', description: 'Quad Half-H Driver', refDesPrefix: 'U',
    defaultProperties: { value: 'L293D', package: 'DIP-16' },
    pins: [ ...createPins(8, 'left', 1), ...createPins(8, 'right', 9) ] },
  { type: '74hc14', label: '74HC14 Hex Inverter', category: 'ic', description: 'Schmitt Trigger Inverter', refDesPrefix: 'U',
    defaultProperties: { value: '74HC14', package: 'SOIC-14' },
    pins: [ ...createPins(7, 'left', 1), ...createPins(7, 'right', 8) ] },
  { type: 'cd4017', label: 'CD4017 Decade Counter', category: 'ic', description: 'Johnson Counter', refDesPrefix: 'U',
    defaultProperties: { value: 'CD4017', package: 'DIP-16' },
    pins: [ ...createPins(8, 'left', 1), ...createPins(8, 'right', 9) ] },
  { type: 'uln2003', label: 'ULN2003 Darlington Array', category: 'ic', description: '7-Ch Darlington Sink Driver', refDesPrefix: 'U',
    defaultProperties: { value: 'ULN2003A', package: 'SOP-16' },
    pins: [ ...createPins(8, 'left', 1), ...createPins(8, 'right', 9) ] },
  { type: 'max232', label: 'MAX232 RS232 Driver', category: 'ic', description: 'RS-232 Transceiver', refDesPrefix: 'U',
    defaultProperties: { value: 'MAX232', package: 'SOIC-16' },
    pins: [ ...createPins(8, 'left', 1), ...createPins(8, 'right', 9) ] },
  { type: 'lm324', label: 'LM324 Quad Op-Amp', category: 'ic', description: 'Quad Operational Amplifier', refDesPrefix: 'U',
    defaultProperties: { value: 'LM324', package: 'SOIC-14' },
    pins: [ ...createPins(7, 'left', 1), ...createPins(7, 'right', 8) ] },

  // ── Connectors & Electromechanical ─────────────────────────────────────────
  { type: 'header', label: 'Pin Header (1x4)', category: 'connector', description: '2.54mm pin header', refDesPrefix: 'J',
    defaultProperties: { value: '1x4', pitch: '2.54mm' },
    pins: createPins(4, 'right', 1) },
  { type: 'usb', label: 'USB-C Receptacle', category: 'connector', description: 'USB Type-C', refDesPrefix: 'J',
    defaultProperties: { value: 'USB-C (16-pin)', package: 'SMD' },
    pins: [ ...createPins(8, 'left', 1, 'A'), ...createPins(8, 'right', 1, 'B') ] },
  { type: 'switch', label: 'Push Button', category: 'connector', description: 'Momentary Tactile Switch', refDesPrefix: 'SW',
    defaultProperties: { value: '6x6mm', type: 'Tactile' },
    pins: [{ id: '1', label: '1', type: 'bidirectional', side: 'left' }, { id: '2', label: '2', type: 'bidirectional', side: 'right' }] },
  { type: 'barrel', label: 'DC Barrel Jack', category: 'connector', description: '5.5x2.1mm DC Power Jack', refDesPrefix: 'J',
    defaultProperties: { value: '5.5x2.1mm' },
    pins: [{ id: 'pwr', label: 'PWR', type: 'power', side: 'left' }, { id: 'gnd', label: 'GND', type: 'ground', side: 'right' }] },
  { type: 'rj45', label: 'RJ45 Jack', category: 'connector', description: 'Ethernet Jack with Mag', refDesPrefix: 'J',
    defaultProperties: { value: 'RJ45 MagJack', package: 'TH' },
    pins: createPins(8, 'bottom', 1) },
  { type: 'usba', label: 'USB Type-A', category: 'connector', description: 'USB-A Receptacle', refDesPrefix: 'J',
    defaultProperties: { value: 'USB-A 2.0', package: 'TH' },
    pins: createPins(4, 'right', 1) },
  { type: 'termblock2', label: 'Terminal Block (2-Pin)', category: 'connector', description: 'Screw Terminal 5.08mm', refDesPrefix: 'J',
    defaultProperties: { value: '2-Pin 5.08mm', pitch: '5.08mm' },
    pins: createPins(2, 'right', 1) },
  { type: 'termblock3', label: 'Terminal Block (3-Pin)', category: 'connector', description: 'Screw Terminal 5.08mm', refDesPrefix: 'J',
    defaultProperties: { value: '3-Pin 5.08mm', pitch: '5.08mm' },
    pins: createPins(3, 'right', 1) },
  { type: 'audiojack', label: '3.5mm Audio Jack', category: 'connector', description: 'Stereo Audio Jack TRRS', refDesPrefix: 'J',
    defaultProperties: { value: '3.5mm TRRS', package: 'SMD' },
    pins: [{ id: 'tip', label: 'T', type: 'bidirectional', side: 'left' }, { id: 'ring1', label: 'R1', type: 'bidirectional', side: 'left' }, { id: 'ring2', label: 'R2', type: 'bidirectional', side: 'right' }, { id: 'sleeve', label: 'S', type: 'ground', side: 'right' }] },
  { type: 'microusb', label: 'Micro USB Receptacle', category: 'connector', description: 'USB 2.0 Micro-B', refDesPrefix: 'J',
    defaultProperties: { value: 'Micro-B', package: 'SMD' },
    pins: [ ...createPins(3, 'left', 1), ...createPins(2, 'right', 4) ] },
  { type: 'jstxh2', label: 'JST XH (2-Pin)', category: 'connector', description: '2.50mm Pitch Connector', refDesPrefix: 'J',
    defaultProperties: { value: 'JST XH-2', pitch: '2.50mm' },
    pins: createPins(2, 'right', 1) },
  { type: 'jstxh4', label: 'JST XH (4-Pin)', category: 'connector', description: '2.50mm Pitch Connector', refDesPrefix: 'J',
    defaultProperties: { value: 'JST XH-4', pitch: '2.50mm' },
    pins: createPins(4, 'right', 1) },
  { type: 'db9', label: 'D-Sub 9 (DB9)', category: 'connector', description: '9-Pin Serial Connector', refDesPrefix: 'J',
    defaultProperties: { value: 'DB9 Female', package: 'Right Angle' },
    pins: [ ...createPins(5, 'left', 1), ...createPins(4, 'right', 6) ] },

  // ── Power & Ground ─────────────────────────────────────────────────────────
  { type: 'vcc', label: 'VCC (+5V / +3.3V)', category: 'power', description: 'Power supply rail', refDesPrefix: 'PWR',
    defaultProperties: { value: '+5V' },
    pins: [{ id: '1', label: 'VCC', type: 'power', side: 'bottom' }] },
  { type: 'gnd', label: 'GND (Ground)', category: 'power', description: 'Ground reference', refDesPrefix: 'GND',
    defaultProperties: { value: 'GND', type: 'Signal' },
    pins: [{ id: '1', label: 'GND', type: 'ground', side: 'top' }] },
  { type: 'battery', label: 'Coin Cell Holder', category: 'power', description: 'CR2032 Battery Holder', refDesPrefix: 'BT',
    defaultProperties: { value: 'CR2032', capacity: '220mAh' },
    pins: [{ id: 'plus', label: '+', type: 'power', side: 'left' }, { id: 'minus', label: '−', type: 'ground', side: 'right' }] },
  { type: 'battery18650', label: '18650 Battery Holder', category: 'power', description: 'Single 18650 Cell', refDesPrefix: 'BT',
    defaultProperties: { value: '18650', capacity: '2600mAh' },
    pins: [{ id: 'plus', label: '+', type: 'power', side: 'left' }, { id: 'minus', label: '−', type: 'ground', side: 'right' }] },
  { type: 'solar', label: 'Solar Panel Input', category: 'power', description: 'Generic Solar Panel Header', refDesPrefix: 'PV',
    defaultProperties: { value: '5V 1W', package: 'Header' },
    pins: [{ id: 'plus', label: '+', type: 'power', side: 'left' }, { id: 'minus', label: '−', type: 'ground', side: 'right' }] },

  // ── Sensors & Misc ─────────────────────────────────────────────────────────
  { type: 'testPoint', label: 'Test Point', category: 'sensor', description: 'Board test point / Via', refDesPrefix: 'TP',
    defaultProperties: { value: 'TP' },
    pins: [{ id: '1', label: '1', type: 'bidirectional', side: 'bottom' }] },
  { type: 'mpu6050', label: 'MPU6050 (IMU)', category: 'sensor', description: '6-Axis Accel/Gyro Module', refDesPrefix: 'U',
    defaultProperties: { value: 'MPU6050' },
    pins: [ ...createPins(4, 'left', 1), ...createPins(4, 'right', 5) ] },
  { type: 'dht11', label: 'DHT11 Temp/Humid', category: 'sensor', description: 'Temp & Humidity Sensor', refDesPrefix: 'U',
    defaultProperties: { value: 'DHT11' },
    pins: [ ...createPins(4, 'bottom', 1) ] },
  { type: 'hcsr04', label: 'HC-SR04 Ultrasonic', category: 'sensor', description: 'Distance Sensor Module', refDesPrefix: 'U',
    defaultProperties: { value: 'HC-SR04' },
    pins: [ ...createPins(4, 'bottom', 1) ] },
  { type: 'ds18b20', label: 'DS18B20 Temp Sensor', category: 'sensor', description: '1-Wire Digital Thermometer', refDesPrefix: 'U',
    defaultProperties: { value: 'DS18B20', package: 'TO-92' },
    pins: [ ...createPins(3, 'bottom', 1) ] },
  { type: 'relay', label: 'Relay (SPDT)', category: 'sensor', description: 'Electromechanical Relay 5V', refDesPrefix: 'K',
    defaultProperties: { value: 'SRD-05VDC-SL-C', package: 'THT' },
    pins: [{ id: 'coil1', label: 'C1', type: 'input', side: 'left' }, { id: 'coil2', label: 'C2', type: 'ground', side: 'left' }, { id: 'com', label: 'COM', type: 'bidirectional', side: 'bottom' }, { id: 'no', label: 'NO', type: 'output', side: 'right' }, { id: 'nc', label: 'NC', type: 'output', side: 'top' }] },

  // ── Boards (Templates) ─────────────────────────────────────────────────────
  { type: 'board_custom', label: 'Custom Resizable Board', category: 'board', description: 'Custom sized PCB', refDesPrefix: 'BRD',
    defaultProperties: { width: 800, height: 600, outline: 'rectangular' },
    pins: [] },
  { type: 'board_100x100', label: 'Standard 100x100mm', category: 'board', description: 'Standard Eurocard size (approx)', refDesPrefix: 'BRD',
    defaultProperties: { width: 1000, height: 1000, outline: 'rectangular' },
    pins: [] },
  { type: 'board_50x50', label: 'Standard 50x50mm', category: 'board', description: 'Small square board', refDesPrefix: 'BRD',
    defaultProperties: { width: 500, height: 500, outline: 'rectangular' },
    pins: [] },
  { type: 'board_uno', label: 'Arduino Uno Shield', category: 'board', description: 'Arduino Uno compatible shield outline', refDesPrefix: 'BRD',
    defaultProperties: { width: 686, height: 533, outline: 'uno' },
    pins: [] },
  { type: 'board_hat', label: 'Raspberry Pi HAT', category: 'board', description: 'Raspberry Pi HAT outline', refDesPrefix: 'BRD',
    defaultProperties: { width: 650, height: 560, outline: 'hat' },
    pins: [] },
  { type: 'copper_pour', label: 'Copper Pour (GND)', category: 'board', description: 'Resizable Copper Area', refDesPrefix: 'POUR',
    defaultProperties: { width: 400, height: 400, net: 'GND' },
    pins: [{ id: 'gnd', label: 'GND', type: 'ground', side: 'top' }] },
];

// ── Helpers ──────────────────────────────────────────────────────────────────

export function getCatalogEntry(type: string): CatalogEntry | undefined {
  return COMPONENT_CATALOG.find(c => c.type === type);
}

export function getCatalogByCategory(category: ComponentCategory): CatalogEntry[] {
  return COMPONENT_CATALOG.filter(c => c.category === category);
}

export const CATEGORY_LABELS: Record<ComponentCategory, string> = {
  passive: 'Passive Components',
  active: 'Active Semiconductors',
  ic: 'ICs & Digital',
  connector: 'Connectors',
  power: 'Power & Ground',
  sensor: 'Sensors & Misc',
  board: 'PCB Boards',
};

export const CATEGORY_ORDER: ComponentCategory[] = ['board', 'passive', 'active', 'ic', 'connector', 'power', 'sensor'];
