"""Add placement and survey models for NAAC

Revision ID: 0392bb4deeac
Revises: 4a9eb05a69f9
Create Date: 2026-05-09 13:48:22.637971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0392bb4deeac'
down_revision: Union[str, Sequence[str], None] = '4a9eb05a69f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey_templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('survey_type', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_survey_templates_college_id'), 'survey_templates', ['college_id'], unique=False)
    op.create_index(op.f('ix_survey_templates_id'), 'survey_templates', ['id'], unique=False)
    op.create_index(op.f('ix_survey_templates_is_deleted'), 'survey_templates', ['is_deleted'], unique=False)
    op.create_table('higher_education_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('institution_name', sa.String(), nullable=False),
    sa.Column('program_name', sa.String(), nullable=False),
    sa.Column('admission_proof', sa.String(), nullable=True),
    sa.Column('admitted_on', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_higher_education_records_college_id'), 'higher_education_records', ['college_id'], unique=False)
    op.create_index(op.f('ix_higher_education_records_id'), 'higher_education_records', ['id'], unique=False)
    op.create_index(op.f('ix_higher_education_records_is_deleted'), 'higher_education_records', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_higher_education_records_student_id'), 'higher_education_records', ['student_id'], unique=False)
    op.create_table('placement_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('package', sa.Float(), nullable=True),
    sa.Column('offer_letter_url', sa.String(), nullable=True),
    sa.Column('placed_on', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_placement_records_college_id'), 'placement_records', ['college_id'], unique=False)
    op.create_index(op.f('ix_placement_records_id'), 'placement_records', ['id'], unique=False)
    op.create_index(op.f('ix_placement_records_is_deleted'), 'placement_records', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_placement_records_student_id'), 'placement_records', ['student_id'], unique=False)
    op.create_table('student_satisfaction_surveys',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('responses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'academic_year', name='uq_sss')
    )
    op.create_index('ix_sss_college_year', 'student_satisfaction_surveys', ['college_id', 'academic_year'], unique=False)
    op.create_index(op.f('ix_student_satisfaction_surveys_college_id'), 'student_satisfaction_surveys', ['college_id'], unique=False)
    op.create_index(op.f('ix_student_satisfaction_surveys_id'), 'student_satisfaction_surveys', ['id'], unique=False)
    op.create_index(op.f('ix_student_satisfaction_surveys_is_deleted'), 'student_satisfaction_surveys', ['is_deleted'], unique=False)
    op.create_table('survey_questions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('order_index', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['survey_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_survey_questions_id'), 'survey_questions', ['id'], unique=False)
    op.create_index(op.f('ix_survey_questions_is_deleted'), 'survey_questions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_survey_questions_template_id'), 'survey_questions', ['template_id'], unique=False)
    op.create_table('survey_responses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['survey_templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_survey_responses_id'), 'survey_responses', ['id'], unique=False)
    op.create_index(op.f('ix_survey_responses_is_deleted'), 'survey_responses', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_survey_responses_template_id'), 'survey_responses', ['template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    op.drop_index(op.f('ix_survey_responses_template_id'), table_name='survey_responses')
    op.drop_index(op.f('ix_survey_responses_is_deleted'), table_name='survey_responses')
    op.drop_index(op.f('ix_survey_responses_id'), table_name='survey_responses')
    op.drop_table('survey_responses')
    op.drop_index(op.f('ix_survey_questions_template_id'), table_name='survey_questions')
    op.drop_index(op.f('ix_survey_questions_is_deleted'), table_name='survey_questions')
    op.drop_index(op.f('ix_survey_questions_id'), table_name='survey_questions')
    op.drop_table('survey_questions')
    op.drop_index(op.f('ix_student_satisfaction_surveys_is_deleted'), table_name='student_satisfaction_surveys')
    op.drop_index(op.f('ix_student_satisfaction_surveys_id'), table_name='student_satisfaction_surveys')
    op.drop_index(op.f('ix_student_satisfaction_surveys_college_id'), table_name='student_satisfaction_surveys')
    op.drop_index('ix_sss_college_year', table_name='student_satisfaction_surveys')
    op.drop_table('student_satisfaction_surveys')
    op.drop_index(op.f('ix_placement_records_student_id'), table_name='placement_records')
    op.drop_index(op.f('ix_placement_records_is_deleted'), table_name='placement_records')
    op.drop_index(op.f('ix_placement_records_id'), table_name='placement_records')
    op.drop_index(op.f('ix_placement_records_college_id'), table_name='placement_records')
    op.drop_table('placement_records')
    op.drop_index(op.f('ix_higher_education_records_student_id'), table_name='higher_education_records')
    op.drop_index(op.f('ix_higher_education_records_is_deleted'), table_name='higher_education_records')
    op.drop_index(op.f('ix_higher_education_records_id'), table_name='higher_education_records')
    op.drop_index(op.f('ix_higher_education_records_college_id'), table_name='higher_education_records')
    op.drop_table('higher_education_records')
    op.drop_index(op.f('ix_survey_templates_is_deleted'), table_name='survey_templates')
    op.drop_index(op.f('ix_survey_templates_id'), table_name='survey_templates')
    op.drop_index(op.f('ix_survey_templates_college_id'), table_name='survey_templates')
    op.drop_table('survey_templates')
    # ### end Alembic commands ###
