"""add_visitor_management_tables

Revision ID: 047ebaf36580
Revises: 24faa9aa79e7
Create Date: 2026-04-15 14:15:11.975270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '047ebaf36580'
down_revision: Union[str, Sequence[str], None] = '24faa9aa79e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visitors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('id_proof_type', sa.String(), nullable=True),
    sa.Column('id_proof_number', sa.String(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('visitor_type', sa.String(), server_default='other', nullable=False),
    sa.Column('total_visits', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("visitor_type IN ('parent', 'industry', 'delivery', 'official', 'interview_candidate', 'alumni', 'other')", name='ck_visitor_type'),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_visitor_college_name', 'visitors', ['college_id', 'name'], unique=False)
    op.create_index('ix_visitor_college_phone', 'visitors', ['college_id', 'phone'], unique=False)
    op.create_index(op.f('ix_visitors_id'), 'visitors', ['id'], unique=False)
    op.create_index(op.f('ix_visitors_is_deleted'), 'visitors', ['is_deleted'], unique=False)
    op.create_table('visit_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('visitor_id', sa.String(), nullable=False),
    sa.Column('gate_type', sa.String(), server_default='main_gate', nullable=False),
    sa.Column('hostel_id', sa.String(), nullable=True),
    sa.Column('host_id', sa.String(), nullable=True),
    sa.Column('host_name', sa.String(), nullable=True),
    sa.Column('host_department', sa.String(), nullable=True),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('visit_type', sa.String(), server_default='walk_in', nullable=False),
    sa.Column('status', sa.String(), server_default='pending', nullable=False),
    sa.Column('num_accompanying', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('vehicle_number', sa.String(), nullable=True),
    sa.Column('badge_number', sa.String(), nullable=True),
    sa.Column('expected_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_departure', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checked_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checked_in_by', sa.String(), nullable=True),
    sa.Column('checked_out_by', sa.String(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("gate_type IN ('main_gate', 'hostel')", name='ck_visit_gate_type'),
    sa.CheckConstraint("status IN ('pending', 'pre_approved', 'approved', 'checked_in', 'checked_out', 'rejected', 'expired')", name='ck_visit_status'),
    sa.CheckConstraint("visit_type IN ('walk_in', 'pre_approved')", name='ck_visit_type'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['checked_in_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['checked_out_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hostel_id'], ['hostels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_visit_college_status', 'visit_records', ['college_id', 'status'], unique=False)
    op.create_index('ix_visit_gate_type', 'visit_records', ['college_id', 'gate_type', 'status'], unique=False)
    op.create_index('ix_visit_host', 'visit_records', ['host_id', 'status'], unique=False)
    op.create_index('ix_visit_hostel', 'visit_records', ['hostel_id', 'status'], unique=False, postgresql_where=sa.text('hostel_id IS NOT NULL'))
    op.create_index(op.f('ix_visit_records_id'), 'visit_records', ['id'], unique=False)
    op.create_index(op.f('ix_visit_records_is_deleted'), 'visit_records', ['is_deleted'], unique=False)
    op.create_index('ix_visit_visitor_date', 'visit_records', ['visitor_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_visit_visitor_date', table_name='visit_records')
    op.drop_index(op.f('ix_visit_records_is_deleted'), table_name='visit_records')
    op.drop_index(op.f('ix_visit_records_id'), table_name='visit_records')
    op.drop_index('ix_visit_hostel', table_name='visit_records', postgresql_where=sa.text('hostel_id IS NOT NULL'))
    op.drop_index('ix_visit_host', table_name='visit_records')
    op.drop_index('ix_visit_gate_type', table_name='visit_records')
    op.drop_index('ix_visit_college_status', table_name='visit_records')
    op.drop_table('visit_records')
    op.drop_index(op.f('ix_visitors_is_deleted'), table_name='visitors')
    op.drop_index(op.f('ix_visitors_id'), table_name='visitors')
    op.drop_index('ix_visitor_college_phone', table_name='visitors')
    op.drop_index('ix_visitor_college_name', table_name='visitors')
    op.drop_table('visitors')
    # ### end Alembic commands ###
