"""add_iot_tables_bus_vending_rewards

Revision ID: 0ff4c80840a6
Revises: 59002adb0ab6
Create Date: 2026-04-14 20:47:56.350738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ff4c80840a6'
down_revision: Union[str, Sequence[str], None] = '59002adb0ab6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vending_machines',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('machine_code', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('esp32_ip', sa.String(), nullable=True),
    sa.Column('inventory', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('status', sa.String(), server_default='online', nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('online', 'offline', 'maintenance')", name='ck_vending_status'),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('machine_code')
    )
    op.create_index(op.f('ix_vending_machines_college_id'), 'vending_machines', ['college_id'], unique=False)
    op.create_index(op.f('ix_vending_machines_id'), 'vending_machines', ['id'], unique=False)
    op.create_index(op.f('ix_vending_machines_is_deleted'), 'vending_machines', ['is_deleted'], unique=False)
    op.create_table('bus_routes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('route_number', sa.String(), nullable=False),
    sa.Column('route_name', sa.String(), nullable=True),
    sa.Column('driver_id', sa.String(), nullable=True),
    sa.Column('stops', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('departure_time', sa.String(), nullable=True),
    sa.Column('return_time', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('college_id', 'route_number', name='uq_bus_route_number')
    )
    op.create_index(op.f('ix_bus_routes_college_id'), 'bus_routes', ['college_id'], unique=False)
    op.create_index(op.f('ix_bus_routes_id'), 'bus_routes', ['id'], unique=False)
    op.create_index(op.f('ix_bus_routes_is_deleted'), 'bus_routes', ['is_deleted'], unique=False)
    op.create_table('reward_point_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reward_point_logs_id'), 'reward_point_logs', ['id'], unique=False)
    op.create_index('ix_reward_student_time', 'reward_point_logs', ['student_id', 'created_at'], unique=False)
    op.create_table('vending_transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('machine_id', sa.String(), nullable=True),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('balance_after', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['machine_id'], ['vending_machines.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vending_transactions_id'), 'vending_transactions', ['id'], unique=False)
    op.create_index('ix_vending_txn_student', 'vending_transactions', ['student_id', 'recorded_at'], unique=False)
    op.create_table('bus_locations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('route_id', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('speed_kmh', sa.Float(), nullable=True),
    sa.Column('heading', sa.Float(), nullable=True),
    sa.Column('geofence_event', sa.String(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['route_id'], ['bus_routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bus_locations_id'), 'bus_locations', ['id'], unique=False)
    op.create_index('ix_busloc_route_time', 'bus_locations', ['route_id', 'recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_busloc_route_time', table_name='bus_locations')
    op.drop_index(op.f('ix_bus_locations_id'), table_name='bus_locations')
    op.drop_table('bus_locations')
    op.drop_index('ix_vending_txn_student', table_name='vending_transactions')
    op.drop_index(op.f('ix_vending_transactions_id'), table_name='vending_transactions')
    op.drop_table('vending_transactions')
    op.drop_index('ix_reward_student_time', table_name='reward_point_logs')
    op.drop_index(op.f('ix_reward_point_logs_id'), table_name='reward_point_logs')
    op.drop_table('reward_point_logs')
    op.drop_index(op.f('ix_bus_routes_is_deleted'), table_name='bus_routes')
    op.drop_index(op.f('ix_bus_routes_id'), table_name='bus_routes')
    op.drop_index(op.f('ix_bus_routes_college_id'), table_name='bus_routes')
    op.drop_table('bus_routes')
    op.drop_index(op.f('ix_vending_machines_is_deleted'), table_name='vending_machines')
    op.drop_index(op.f('ix_vending_machines_id'), table_name='vending_machines')
    op.drop_index(op.f('ix_vending_machines_college_id'), table_name='vending_machines')
    op.drop_table('vending_machines')
    # ### end Alembic commands ###
