"""Massive feature expansion models

Revision ID: 10faf3870b81
Revises: 4b5c6d7e8f9a
Create Date: 2026-05-06 23:45:31.713574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '10faf3870b81'
down_revision: Union[str, Sequence[str], None] = '4b5c6d7e8f9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mood_checkins',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('mood_score', sa.Integer(), nullable=False),
    sa.Column('energy_score', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mood_checkins_id'), 'mood_checkins', ['id'], unique=False)
    op.create_index(op.f('ix_mood_checkins_is_deleted'), 'mood_checkins', ['is_deleted'], unique=False)
    op.create_index('ix_mood_student', 'mood_checkins', ['student_id', 'created_at'], unique=False)
    op.create_table('flashcard_decks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('course_id', sa.String(), nullable=True),
    sa.Column('creator_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flashcard_decks_id'), 'flashcard_decks', ['id'], unique=False)
    op.create_index(op.f('ix_flashcard_decks_is_deleted'), 'flashcard_decks', ['is_deleted'], unique=False)
    op.create_table('flashcards',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('deck_id', sa.String(), nullable=False),
    sa.Column('front_text', sa.Text(), nullable=False),
    sa.Column('back_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['deck_id'], ['flashcard_decks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flashcards_id'), 'flashcards', ['id'], unique=False)
    op.create_index(op.f('ix_flashcards_is_deleted'), 'flashcards', ['is_deleted'], unique=False)
    op.create_table('flashcard_reviews',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('card_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('next_review_date', sa.Date(), nullable=False),
    sa.Column('easiness_factor', sa.Float(), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['flashcards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_id', 'student_id', name='uq_flashcard_review')
    )
    op.create_index('ix_flashcard_review_student_date', 'flashcard_reviews', ['student_id', 'next_review_date'], unique=False)
    op.create_index(op.f('ix_flashcard_reviews_id'), 'flashcard_reviews', ['id'], unique=False)
    op.add_column('user_profiles', sa.Column('xp_points', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('user_profiles', sa.Column('current_streak', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('user_profiles', sa.Column('longest_streak', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('user_profiles', sa.Column('last_active_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'last_active_date')
    op.drop_column('user_profiles', 'longest_streak')
    op.drop_column('user_profiles', 'current_streak')
    op.drop_column('user_profiles', 'xp_points')
    op.drop_index(op.f('ix_flashcard_reviews_id'), table_name='flashcard_reviews')
    op.drop_index('ix_flashcard_review_student_date', table_name='flashcard_reviews')
    op.drop_table('flashcard_reviews')
    op.drop_index(op.f('ix_flashcards_is_deleted'), table_name='flashcards')
    op.drop_index(op.f('ix_flashcards_id'), table_name='flashcards')
    op.drop_table('flashcards')
    op.drop_index(op.f('ix_flashcard_decks_is_deleted'), table_name='flashcard_decks')
    op.drop_index(op.f('ix_flashcard_decks_id'), table_name='flashcard_decks')
    op.drop_table('flashcard_decks')
    op.drop_index('ix_mood_student', table_name='mood_checkins')
    op.drop_index(op.f('ix_mood_checkins_is_deleted'), table_name='mood_checkins')
    op.drop_index(op.f('ix_mood_checkins_id'), table_name='mood_checkins')
    op.drop_table('mood_checkins')
    # ### end Alembic commands ###
