"""add_library_management

Revision ID: 24faa9aa79e7
Revises: 333b1f2e2298
Create Date: 2026-04-15 10:01:53.301069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '24faa9aa79e7'
down_revision: Union[str, Sequence[str], None] = '333b1f2e2298'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('isbn', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('publisher', sa.String(), nullable=True),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_image_url', sa.String(), nullable=True),
    sa.Column('total_copies', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('available_copies', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('max_checkout_days', sa.Integer(), server_default=sa.text('14'), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('college_id', 'isbn', name='uq_book_isbn_college')
    )
    op.create_index('ix_books_category', 'books', ['college_id', 'category'], unique=False)
    op.create_index(op.f('ix_books_college_id'), 'books', ['college_id'], unique=False)
    op.create_index(op.f('ix_books_id'), 'books', ['id'], unique=False)
    op.create_index(op.f('ix_books_is_deleted'), 'books', ['is_deleted'], unique=False)
    op.create_index('ix_books_search', 'books', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_table('book_copies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('book_id', sa.String(), nullable=False),
    sa.Column('barcode', sa.String(), nullable=False),
    sa.Column('rfid_tag', sa.String(), nullable=True),
    sa.Column('shelf_location', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default='AVAILABLE', nullable=False),
    sa.Column('condition_notes', sa.Text(), nullable=True),
    sa.Column('acquired_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('AVAILABLE', 'CHECKED_OUT', 'RESERVED', 'MAINTENANCE', 'LOST')", name='ck_bookcopy_status'),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode'),
    sa.UniqueConstraint('rfid_tag')
    )
    op.create_index(op.f('ix_book_copies_college_id'), 'book_copies', ['college_id'], unique=False)
    op.create_index(op.f('ix_book_copies_id'), 'book_copies', ['id'], unique=False)
    op.create_index(op.f('ix_book_copies_is_deleted'), 'book_copies', ['is_deleted'], unique=False)
    op.create_index('ix_bookcopy_book_status', 'book_copies', ['book_id', 'status'], unique=False)
    op.create_table('library_reservations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('book_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default='PENDING', nullable=False),
    sa.Column('reserved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('PENDING', 'READY', 'FULFILLED', 'EXPIRED', 'CANCELLED')", name='ck_libreserve_status'),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_library_reservations_college_id'), 'library_reservations', ['college_id'], unique=False)
    op.create_index(op.f('ix_library_reservations_id'), 'library_reservations', ['id'], unique=False)
    op.create_index(op.f('ix_library_reservations_is_deleted'), 'library_reservations', ['is_deleted'], unique=False)
    op.create_index('ix_libreserve_book_status', 'library_reservations', ['book_id', 'status'], unique=False)
    op.create_index('ix_libreserve_user', 'library_reservations', ['user_id', 'status'], unique=False)
    op.create_table('library_transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('copy_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('checkout_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('return_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), server_default='ACTIVE', nullable=False),
    sa.Column('renewed_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('ACTIVE', 'RETURNED', 'OVERDUE')", name='ck_libtxn_status'),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['copy_id'], ['book_copies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_library_transactions_college_id'), 'library_transactions', ['college_id'], unique=False)
    op.create_index(op.f('ix_library_transactions_id'), 'library_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_library_transactions_is_deleted'), 'library_transactions', ['is_deleted'], unique=False)
    op.create_index('ix_libtxn_copy_active', 'library_transactions', ['copy_id', 'status'], unique=False)
    op.create_index('ix_libtxn_due', 'library_transactions', ['due_date'], unique=False, postgresql_where=sa.text("status = 'ACTIVE'"))
    op.create_index('ix_libtxn_user_status', 'library_transactions', ['user_id', 'status'], unique=False)
    op.create_table('library_fines',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(), server_default='UNPAID', nullable=False),
    sa.Column('paid_via', sa.String(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('UNPAID', 'PAID', 'WAIVED')", name='ck_libfine_status'),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['library_transactions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_libfine_user_status', 'library_fines', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_library_fines_college_id'), 'library_fines', ['college_id'], unique=False)
    op.create_index(op.f('ix_library_fines_id'), 'library_fines', ['id'], unique=False)
    op.create_index(op.f('ix_library_fines_is_deleted'), 'library_fines', ['is_deleted'], unique=False)
    # ### end Alembic commands ###

    # ── Manual: Full-text search trigger for books.search_vector ──
    op.execute("""
        CREATE OR REPLACE FUNCTION library_books_search_update() RETURNS trigger AS $$
        BEGIN
            NEW.search_vector :=
                setweight(to_tsvector('english', coalesce(NEW.title, '')), 'A') ||
                setweight(to_tsvector('english', coalesce(NEW.author, '')), 'B') ||
                setweight(to_tsvector('english', coalesce(NEW.publisher, '')), 'C') ||
                setweight(to_tsvector('english', coalesce(NEW.category, '')), 'C');
            RETURN NEW;
        END
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER trg_books_search_update
        BEFORE INSERT OR UPDATE OF title, author, publisher, category
        ON books
        FOR EACH ROW EXECUTE FUNCTION library_books_search_update();
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ── Manual: Drop search trigger ──
    op.execute("DROP TRIGGER IF EXISTS trg_books_search_update ON books;")
    op.execute("DROP FUNCTION IF EXISTS library_books_search_update();")
    op.drop_index(op.f('ix_library_fines_is_deleted'), table_name='library_fines')
    op.drop_index(op.f('ix_library_fines_id'), table_name='library_fines')
    op.drop_index(op.f('ix_library_fines_college_id'), table_name='library_fines')
    op.drop_index('ix_libfine_user_status', table_name='library_fines')
    op.drop_table('library_fines')
    op.drop_index('ix_libtxn_user_status', table_name='library_transactions')
    op.drop_index('ix_libtxn_due', table_name='library_transactions', postgresql_where=sa.text("status = 'ACTIVE'"))
    op.drop_index('ix_libtxn_copy_active', table_name='library_transactions')
    op.drop_index(op.f('ix_library_transactions_is_deleted'), table_name='library_transactions')
    op.drop_index(op.f('ix_library_transactions_id'), table_name='library_transactions')
    op.drop_index(op.f('ix_library_transactions_college_id'), table_name='library_transactions')
    op.drop_table('library_transactions')
    op.drop_index('ix_libreserve_user', table_name='library_reservations')
    op.drop_index('ix_libreserve_book_status', table_name='library_reservations')
    op.drop_index(op.f('ix_library_reservations_is_deleted'), table_name='library_reservations')
    op.drop_index(op.f('ix_library_reservations_id'), table_name='library_reservations')
    op.drop_index(op.f('ix_library_reservations_college_id'), table_name='library_reservations')
    op.drop_table('library_reservations')
    op.drop_index('ix_bookcopy_book_status', table_name='book_copies')
    op.drop_index(op.f('ix_book_copies_is_deleted'), table_name='book_copies')
    op.drop_index(op.f('ix_book_copies_id'), table_name='book_copies')
    op.drop_index(op.f('ix_book_copies_college_id'), table_name='book_copies')
    op.drop_table('book_copies')
    op.drop_index('ix_books_search', table_name='books', postgresql_using='gin')
    op.drop_index(op.f('ix_books_is_deleted'), table_name='books')
    op.drop_index(op.f('ix_books_id'), table_name='books')
    op.drop_index(op.f('ix_books_college_id'), table_name='books')
    op.drop_index('ix_books_category', table_name='books')
    op.drop_table('books')
    # ### end Alembic commands ###
