"""fix_allocation_admission_fk_set_null

Revision ID: 2b2ce6699fb9
Revises: ab11286fb520
Create Date: 2026-04-17 19:00:28.299892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b2ce6699fb9'
down_revision: Union[str, Sequence[str], None] = 'ab11286fb520'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('allocations_admission_id_fkey'), 'allocations', type_='foreignkey')
    op.create_foreign_key(None, 'allocations', 'admissions', ['admission_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'allocations', type_='foreignkey')
    op.create_foreign_key(op.f('allocations_admission_id_fkey'), 'allocations', 'admissions', ['admission_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
