"""Add DataLemur fields to sql_problems

Revision ID: 2d76721ba7fa
Revises: 3ba3b2d0c097
Create Date: 2026-04-23 16:14:37.318707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2d76721ba7fa'
down_revision: Union[str, Sequence[str], None] = '3ba3b2d0c097'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sql_problems', sa.Column('tables_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('sql_problems', sa.Column('example_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('sql_problems', sa.Column('explanation', sa.Text(), nullable=True))
    op.add_column('sql_problems', sa.Column('solution_sql', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sql_problems', 'solution_sql')
    op.drop_column('sql_problems', 'explanation')
    op.drop_column('sql_problems', 'example_output')
    op.drop_column('sql_problems', 'tables_meta')
    # ### end Alembic commands ###
