"""Phase1 permission layer cia template engine subject allocation

Revision ID: 30fdc0b3d569
Revises: 69662ad7dd96
Create Date: 2026-04-06 10:32:38.912219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '30fdc0b3d569'
down_revision: Union[str, Sequence[str], None] = '69662ad7dd96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cia_templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('total_marks', sa.Integer(), nullable=False),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cia_templates_college', 'cia_templates', ['college_id'], unique=False)
    op.create_index(op.f('ix_cia_templates_id'), 'cia_templates', ['id'], unique=False)
    op.create_index(op.f('ix_cia_templates_is_deleted'), 'cia_templates', ['is_deleted'], unique=False)
    op.create_table('subject_cia_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('subject_code', sa.String(), nullable=False),
    sa.Column('subject_name', sa.String(), nullable=True),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('is_consolidation_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['cia_templates.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cia_config_subject_year', 'subject_cia_configs', ['subject_code', 'academic_year', 'college_id'], unique=False)
    op.create_index(op.f('ix_subject_cia_configs_id'), 'subject_cia_configs', ['id'], unique=False)
    op.create_index(op.f('ix_subject_cia_configs_is_deleted'), 'subject_cia_configs', ['is_deleted'], unique=False)
    op.create_table('user_permissions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_permissions_id'), 'user_permissions', ['id'], unique=False)
    op.create_index(op.f('ix_user_permissions_is_deleted'), 'user_permissions', ['is_deleted'], unique=False)
    op.create_index('ix_user_permissions_user_college', 'user_permissions', ['user_id', 'college_id'], unique=False)
    op.add_column('faculty_assignments', sa.Column('academic_year', sa.String(), server_default='2024-25', nullable=True))
    op.add_column('faculty_assignments', sa.Column('credits', sa.Integer(), nullable=True))
    op.add_column('faculty_assignments', sa.Column('hours_per_week', sa.Integer(), nullable=True))
    op.add_column('faculty_assignments', sa.Column('is_lab', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('faculty_assignments', 'is_lab')
    op.drop_column('faculty_assignments', 'hours_per_week')
    op.drop_column('faculty_assignments', 'credits')
    op.drop_column('faculty_assignments', 'academic_year')
    op.drop_index('ix_user_permissions_user_college', table_name='user_permissions')
    op.drop_index(op.f('ix_user_permissions_is_deleted'), table_name='user_permissions')
    op.drop_index(op.f('ix_user_permissions_id'), table_name='user_permissions')
    op.drop_table('user_permissions')
    op.drop_index(op.f('ix_subject_cia_configs_is_deleted'), table_name='subject_cia_configs')
    op.drop_index(op.f('ix_subject_cia_configs_id'), table_name='subject_cia_configs')
    op.drop_index('ix_cia_config_subject_year', table_name='subject_cia_configs')
    op.drop_table('subject_cia_configs')
    op.drop_index(op.f('ix_cia_templates_is_deleted'), table_name='cia_templates')
    op.drop_index(op.f('ix_cia_templates_id'), table_name='cia_templates')
    op.drop_index('ix_cia_templates_college', table_name='cia_templates')
    op.drop_table('cia_templates')
    # ### end Alembic commands ###
