"""add_transport_tables_ais140_enrollment_trips

Revision ID: 333b1f2e2298
Revises: 0ff4c80840a6
Create Date: 2026-04-14 23:57:22.625923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '333b1f2e2298'
down_revision: Union[str, Sequence[str], None] = '0ff4c80840a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ais140_devices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('imei', sa.String(), nullable=False),
    sa.Column('sim_iccid', sa.String(), nullable=True),
    sa.Column('vehicle_number', sa.String(), nullable=True),
    sa.Column('route_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default='active', nullable=False),
    sa.Column('last_ping_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['route_id'], ['bus_routes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('imei')
    )
    op.create_index(op.f('ix_ais140_devices_college_id'), 'ais140_devices', ['college_id'], unique=False)
    op.create_index(op.f('ix_ais140_devices_id'), 'ais140_devices', ['id'], unique=False)
    op.create_index(op.f('ix_ais140_devices_is_deleted'), 'ais140_devices', ['is_deleted'], unique=False)
    op.create_index('ix_ais140_imei', 'ais140_devices', ['imei'], unique=False)
    op.create_table('transport_enrollments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('route_id', sa.String(), nullable=False),
    sa.Column('boarding_stop_index', sa.Integer(), nullable=False),
    sa.Column('boarding_stop_name', sa.String(), nullable=True),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('fee_paid', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['route_id'], ['bus_routes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'route_id', 'academic_year', name='uq_transport_enrollment')
    )
    op.create_index('ix_transport_enroll_route', 'transport_enrollments', ['route_id', 'boarding_stop_index'], unique=False)
    op.create_index(op.f('ix_transport_enrollments_college_id'), 'transport_enrollments', ['college_id'], unique=False)
    op.create_index(op.f('ix_transport_enrollments_id'), 'transport_enrollments', ['id'], unique=False)
    op.create_index(op.f('ix_transport_enrollments_is_deleted'), 'transport_enrollments', ['is_deleted'], unique=False)
    op.create_table('trips',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('route_id', sa.String(), nullable=False),
    sa.Column('driver_id', sa.String(), nullable=True),
    sa.Column('state', sa.String(), server_default='started', nullable=False),
    sa.Column('direction', sa.String(), server_default='morning', nullable=False),
    sa.Column('current_node_index', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['route_id'], ['bus_routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trip_route_state', 'trips', ['route_id', 'state'], unique=False)
    op.create_index(op.f('ix_trips_id'), 'trips', ['id'], unique=False)
    op.create_table('transport_attendance',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('trip_id', sa.String(), nullable=False),
    sa.Column('route_id', sa.String(), nullable=False),
    sa.Column('boarded_at_stop', sa.Integer(), nullable=True),
    sa.Column('scan_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['route_id'], ['bus_routes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'trip_id', name='uq_transport_attendance')
    )
    op.create_index('ix_transport_att_trip', 'transport_attendance', ['trip_id'], unique=False)
    op.create_index(op.f('ix_transport_attendance_id'), 'transport_attendance', ['id'], unique=False)
    op.create_table('trip_summaries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('trip_id', sa.String(), nullable=False),
    sa.Column('route_id', sa.String(), nullable=False),
    sa.Column('driver_id', sa.String(), nullable=True),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('stops_visited', sa.Integer(), nullable=True),
    sa.Column('total_stops', sa.Integer(), nullable=True),
    sa.Column('max_speed_kmh', sa.Float(), nullable=True),
    sa.Column('delay_minutes', sa.Integer(), nullable=True),
    sa.Column('incidents', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['route_id'], ['bus_routes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_summaries_id'), 'trip_summaries', ['id'], unique=False)
    op.create_index('ix_tripsummary_route_date', 'trip_summaries', ['route_id', 'date'], unique=False)
    op.add_column('bus_routes', sa.Column('vehicle_number', sa.String(), nullable=True))
    op.add_column('bus_routes', sa.Column('capacity', sa.Integer(), nullable=True))
    op.add_column('bus_routes', sa.Column('avg_stop_times', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('bus_routes', sa.Column('fee_amount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bus_routes', 'fee_amount')
    op.drop_column('bus_routes', 'avg_stop_times')
    op.drop_column('bus_routes', 'capacity')
    op.drop_column('bus_routes', 'vehicle_number')
    op.drop_index('ix_tripsummary_route_date', table_name='trip_summaries')
    op.drop_index(op.f('ix_trip_summaries_id'), table_name='trip_summaries')
    op.drop_table('trip_summaries')
    op.drop_index(op.f('ix_transport_attendance_id'), table_name='transport_attendance')
    op.drop_index('ix_transport_att_trip', table_name='transport_attendance')
    op.drop_table('transport_attendance')
    op.drop_index(op.f('ix_trips_id'), table_name='trips')
    op.drop_index('ix_trip_route_state', table_name='trips')
    op.drop_table('trips')
    op.drop_index(op.f('ix_transport_enrollments_is_deleted'), table_name='transport_enrollments')
    op.drop_index(op.f('ix_transport_enrollments_id'), table_name='transport_enrollments')
    op.drop_index(op.f('ix_transport_enrollments_college_id'), table_name='transport_enrollments')
    op.drop_index('ix_transport_enroll_route', table_name='transport_enrollments')
    op.drop_table('transport_enrollments')
    op.drop_index('ix_ais140_imei', table_name='ais140_devices')
    op.drop_index(op.f('ix_ais140_devices_is_deleted'), table_name='ais140_devices')
    op.drop_index(op.f('ix_ais140_devices_id'), table_name='ais140_devices')
    op.drop_index(op.f('ix_ais140_devices_college_id'), table_name='ais140_devices')
    op.drop_table('ais140_devices')
    # ### end Alembic commands ###
