"""Add placement prep depth models

Revision ID: 3ba3b2d0c097
Revises: c50b0cb57389
Create Date: 2026-04-22 13:53:34.682474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ba3b2d0c097'
down_revision: Union[str, Sequence[str], None] = 'c50b0cb57389'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aptitude_questions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('subcategory', sa.String(), nullable=True),
    sa.Column('difficulty', sa.String(), server_default='medium', nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correct_option', sa.String(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aptitude_questions_category'), 'aptitude_questions', ['category'], unique=False)
    op.create_index(op.f('ix_aptitude_questions_id'), 'aptitude_questions', ['id'], unique=False)
    op.create_index(op.f('ix_aptitude_questions_is_deleted'), 'aptitude_questions', ['is_deleted'], unique=False)
    op.create_table('company_interview_experiences',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('target_role', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('difficulty_rating', sa.Integer(), nullable=True),
    sa.Column('rounds', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_interview_experiences_company_name'), 'company_interview_experiences', ['company_name'], unique=False)
    op.create_index(op.f('ix_company_interview_experiences_id'), 'company_interview_experiences', ['id'], unique=False)
    op.create_index(op.f('ix_company_interview_experiences_is_deleted'), 'company_interview_experiences', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_company_interview_experiences_target_role'), 'company_interview_experiences', ['target_role'], unique=False)
    op.create_table('company_question_banks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('exam_name', sa.String(), nullable=False),
    sa.Column('exam_pattern', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('questions', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_question_banks_company_name'), 'company_question_banks', ['company_name'], unique=False)
    op.create_index(op.f('ix_company_question_banks_id'), 'company_question_banks', ['id'], unique=False)
    op.create_index(op.f('ix_company_question_banks_is_deleted'), 'company_question_banks', ['is_deleted'], unique=False)
    op.create_table('sql_problems',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('dataset_theme', sa.String(), nullable=False),
    sa.Column('company_tag', sa.String(), nullable=True),
    sa.Column('difficulty', sa.String(), server_default='medium', nullable=False),
    sa.Column('problem_statement', sa.Text(), nullable=False),
    sa.Column('schema_sql', sa.Text(), nullable=False),
    sa.Column('hint', sa.Text(), nullable=True),
    sa.Column('expected_query', sa.Text(), nullable=False),
    sa.Column('expected_output', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sql_problems_id'), 'sql_problems', ['id'], unique=False)
    op.create_index(op.f('ix_sql_problems_is_deleted'), 'sql_problems', ['is_deleted'], unique=False)
    op.create_table('placement_attempt_trackers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('module_type', sa.String(), nullable=False),
    sa.Column('reference_id', sa.String(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('time_taken_sec', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_placement_attempt_trackers_id'), 'placement_attempt_trackers', ['id'], unique=False)
    op.create_index(op.f('ix_placement_attempt_trackers_is_deleted'), 'placement_attempt_trackers', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_placement_attempt_trackers_student_id'), 'placement_attempt_trackers', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_placement_attempt_trackers_student_id'), table_name='placement_attempt_trackers')
    op.drop_index(op.f('ix_placement_attempt_trackers_is_deleted'), table_name='placement_attempt_trackers')
    op.drop_index(op.f('ix_placement_attempt_trackers_id'), table_name='placement_attempt_trackers')
    op.drop_table('placement_attempt_trackers')
    op.drop_index(op.f('ix_sql_problems_is_deleted'), table_name='sql_problems')
    op.drop_index(op.f('ix_sql_problems_id'), table_name='sql_problems')
    op.drop_table('sql_problems')
    op.drop_index(op.f('ix_company_question_banks_is_deleted'), table_name='company_question_banks')
    op.drop_index(op.f('ix_company_question_banks_id'), table_name='company_question_banks')
    op.drop_index(op.f('ix_company_question_banks_company_name'), table_name='company_question_banks')
    op.drop_table('company_question_banks')
    op.drop_index(op.f('ix_company_interview_experiences_target_role'), table_name='company_interview_experiences')
    op.drop_index(op.f('ix_company_interview_experiences_is_deleted'), table_name='company_interview_experiences')
    op.drop_index(op.f('ix_company_interview_experiences_id'), table_name='company_interview_experiences')
    op.drop_index(op.f('ix_company_interview_experiences_company_name'), table_name='company_interview_experiences')
    op.drop_table('company_interview_experiences')
    op.drop_index(op.f('ix_aptitude_questions_is_deleted'), table_name='aptitude_questions')
    op.drop_index(op.f('ix_aptitude_questions_id'), table_name='aptitude_questions')
    op.drop_index(op.f('ix_aptitude_questions_category'), table_name='aptitude_questions')
    op.drop_table('aptitude_questions')
    # ### end Alembic commands ###
