"""add is_anonymized column to users

Revision ID: 4098389564ad
Revises: 033512191ca8
Create Date: 2026-04-16 03:14:09.609278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4098389564ad'
down_revision: Union[str, Sequence[str], None] = '033512191ca8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_rankings',
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('total_students', sa.Integer(), nullable=False),
    sa.Column('avg_score', sa.Float(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('college_id', 'student_id')
    )
    op.drop_index(op.f('ix_attendance_student_date'), table_name='attendance_records', postgresql_where='(is_deleted = false)')
    op.add_column('audit_logs', sa.Column('college_id', sa.String(), nullable=False))
    op.add_column('audit_logs', sa.Column('resource_type', sa.String(), nullable=False))
    op.add_column('audit_logs', sa.Column('resource_id', sa.String(), nullable=False))
    op.add_column('audit_logs', sa.Column('status', sa.String(), nullable=False))
    op.add_column('audit_logs', sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('audit_logs', sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('audit_logs', sa.Column('ip_address', sa.String(), nullable=True))
    op.add_column('audit_logs', sa.Column('user_agent', sa.String(), nullable=True))
    op.drop_index(op.f('ix_audit_logs_is_deleted'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_user_resource'), table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_college_id'), 'audit_logs', ['college_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.drop_column('audit_logs', 'details')
    op.drop_column('audit_logs', 'deleted_at')
    op.drop_column('audit_logs', 'resource')
    op.drop_column('audit_logs', 'is_deleted')
    op.drop_index(op.f('ix_faculty_assign_teacher'), table_name='faculty_assignments', postgresql_where='(is_deleted = false)')
    op.drop_index(op.f('ix_fees_student_status'), table_name='fee_payments', postgresql_where='(is_deleted = false)')
    op.drop_index(op.f('ix_marks_assignment_exam'), table_name='mark_submissions', postgresql_where='(is_deleted = false)')
    op.drop_index(op.f('ix_attempts_student_quiz'), table_name='quiz_attempts', postgresql_where='(is_deleted = false)')
    op.create_index('ix_sem_grades_college_student', 'semester_grades', ['college_id', 'student_id', 'semester'], unique=False)
    op.drop_index(op.f('ix_timetable_dept_batch_day'), table_name='timetables', postgresql_where='(is_deleted = false)')
    op.add_column('users', sa.Column('is_anonymized', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('anonymized_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('ix_users_college_role_active'), table_name='users', postgresql_where='(is_deleted = false)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_college_role_active'), 'users', ['college_id', 'role'], unique=False, postgresql_where='(is_deleted = false)')
    op.drop_column('users', 'anonymized_at')
    op.drop_column('users', 'is_anonymized')
    op.create_index(op.f('ix_timetable_dept_batch_day'), 'timetables', ['college_id', 'department_id', 'semester', 'day'], unique=False, postgresql_where='(is_deleted = false)')
    op.drop_index('ix_sem_grades_college_student', table_name='semester_grades')
    op.create_index(op.f('ix_attempts_student_quiz'), 'quiz_attempts', ['student_id', 'quiz_id'], unique=False, postgresql_where='(is_deleted = false)')
    op.create_index(op.f('ix_marks_assignment_exam'), 'mark_submissions', ['assignment_id', 'exam_type', 'college_id'], unique=False, postgresql_where='(is_deleted = false)')
    op.create_index(op.f('ix_fees_student_status'), 'fee_payments', ['student_id', 'status', 'college_id'], unique=False, postgresql_where='(is_deleted = false)')
    op.create_index(op.f('ix_faculty_assign_teacher'), 'faculty_assignments', ['teacher_id', 'college_id'], unique=False, postgresql_where='(is_deleted = false)')
    op.add_column('audit_logs', sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('audit_logs', sa.Column('resource', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('audit_logs', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_college_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.create_index(op.f('ix_audit_user_resource'), 'audit_logs', ['user_id', 'resource', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_is_deleted'), 'audit_logs', ['is_deleted'], unique=False)
    op.drop_column('audit_logs', 'user_agent')
    op.drop_column('audit_logs', 'ip_address')
    op.drop_column('audit_logs', 'new_value')
    op.drop_column('audit_logs', 'old_value')
    op.drop_column('audit_logs', 'status')
    op.drop_column('audit_logs', 'resource_id')
    op.drop_column('audit_logs', 'resource_type')
    op.drop_column('audit_logs', 'college_id')
    op.create_index(op.f('ix_attendance_student_date'), 'attendance_records', ['student_id', 'date', 'college_id'], unique=False, postgresql_where='(is_deleted = false)')
    op.drop_table('student_rankings')
    # ### end Alembic commands ###
