"""Add Accreditation Report models

Revision ID: 4a9eb05a69f9
Revises: 10faf3870b81
Create Date: 2026-05-08 22:45:34.854678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a9eb05a69f9'
down_revision: Union[str, Sequence[str], None] = '10faf3870b81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accreditation_report_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('report_type', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('status', sa.String(), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('celery_task_id', sa.String(), nullable=True),
    sa.Column('presigned_url', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('college_id', 'report_type', 'academic_year', 'version', name='uq_report_job_version')
    )
    op.create_index(op.f('ix_accreditation_report_jobs_college_id'), 'accreditation_report_jobs', ['college_id'], unique=False)
    op.create_index(op.f('ix_accreditation_report_jobs_id'), 'accreditation_report_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_accreditation_report_jobs_is_deleted'), 'accreditation_report_jobs', ['is_deleted'], unique=False)
    op.create_index('ix_report_job_college_type', 'accreditation_report_jobs', ['college_id', 'report_type'], unique=False)
    op.create_table('naac_qualitative_narratives',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('criterion_code', sa.String(), nullable=False),
    sa.Column('criterion_name', sa.String(), nullable=False),
    sa.Column('narrative_text', sa.Text(), nullable=True),
    sa.Column('last_edited_by', sa.String(), nullable=True),
    sa.Column('last_edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_complete', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_edited_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('college_id', 'academic_year', 'criterion_code', name='uq_naac_qlm')
    )
    op.create_index('ix_naac_qlm_college_year', 'naac_qualitative_narratives', ['college_id', 'academic_year'], unique=False)
    op.create_index(op.f('ix_naac_qualitative_narratives_college_id'), 'naac_qualitative_narratives', ['college_id'], unique=False)
    op.create_index(op.f('ix_naac_qualitative_narratives_id'), 'naac_qualitative_narratives', ['id'], unique=False)
    op.create_index(op.f('ix_naac_qualitative_narratives_is_deleted'), 'naac_qualitative_narratives', ['is_deleted'], unique=False)
    op.create_table('attainment_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('department_id', sa.String(), nullable=True),
    sa.Column('batch_year', sa.String(), nullable=False),
    sa.Column('direct_threshold_pct', sa.Float(), server_default=sa.text('60.0'), nullable=False),
    sa.Column('direct_weight', sa.Float(), server_default=sa.text('0.80'), nullable=False),
    sa.Column('indirect_weight', sa.Float(), server_default=sa.text('0.20'), nullable=False),
    sa.Column('po_target_level', sa.Float(), server_default=sa.text('2.5'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attainment_cfg_college_dept_batch', 'attainment_configs', ['college_id', 'department_id', 'batch_year'], unique=False)
    op.create_index(op.f('ix_attainment_configs_college_id'), 'attainment_configs', ['college_id'], unique=False)
    op.create_index(op.f('ix_attainment_configs_id'), 'attainment_configs', ['id'], unique=False)
    op.create_index(op.f('ix_attainment_configs_is_deleted'), 'attainment_configs', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attainment_configs_is_deleted'), table_name='attainment_configs')
    op.drop_index(op.f('ix_attainment_configs_id'), table_name='attainment_configs')
    op.drop_index(op.f('ix_attainment_configs_college_id'), table_name='attainment_configs')
    op.drop_index('ix_attainment_cfg_college_dept_batch', table_name='attainment_configs')
    op.drop_table('attainment_configs')
    op.drop_index(op.f('ix_naac_qualitative_narratives_is_deleted'), table_name='naac_qualitative_narratives')
    op.drop_index(op.f('ix_naac_qualitative_narratives_id'), table_name='naac_qualitative_narratives')
    op.drop_index(op.f('ix_naac_qualitative_narratives_college_id'), table_name='naac_qualitative_narratives')
    op.drop_index('ix_naac_qlm_college_year', table_name='naac_qualitative_narratives')
    op.drop_table('naac_qualitative_narratives')
    op.drop_index('ix_report_job_college_type', table_name='accreditation_report_jobs')
    op.drop_index(op.f('ix_accreditation_report_jobs_is_deleted'), table_name='accreditation_report_jobs')
    op.drop_index(op.f('ix_accreditation_report_jobs_id'), table_name='accreditation_report_jobs')
    op.drop_index(op.f('ix_accreditation_report_jobs_college_id'), table_name='accreditation_report_jobs')
    op.drop_table('accreditation_report_jobs')
    # ### end Alembic commands ###
