"""add student_resumes and placement_restrictions tables

Revision ID: 54e44dcc6e76
Revises: 6d5104464501
Create Date: 2026-04-19 16:05:08.067814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54e44dcc6e76'
down_revision: Union[str, Sequence[str], None] = '6d5104464501'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_resumes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('parsed_text', sa.Text(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_student_resume_primary', 'student_resumes', ['student_id', 'is_primary'], unique=False)
    op.create_index(op.f('ix_student_resumes_college_id'), 'student_resumes', ['college_id'], unique=False)
    op.create_index(op.f('ix_student_resumes_id'), 'student_resumes', ['id'], unique=False)
    op.create_index(op.f('ix_student_resumes_is_deleted'), 'student_resumes', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_student_resumes_student_id'), 'student_resumes', ['student_id'], unique=False)
    op.create_table('placement_restrictions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('drive_id', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('restricted_by', sa.String(), nullable=True),
    sa.Column('restriction_type', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['drive_id'], ['placement_drives.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['restricted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_placement_restrictions_college_id'), 'placement_restrictions', ['college_id'], unique=False)
    op.create_index(op.f('ix_placement_restrictions_id'), 'placement_restrictions', ['id'], unique=False)
    op.create_index(op.f('ix_placement_restrictions_is_deleted'), 'placement_restrictions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_placement_restrictions_student_id'), 'placement_restrictions', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_placement_restrictions_student_id'), table_name='placement_restrictions')
    op.drop_index(op.f('ix_placement_restrictions_is_deleted'), table_name='placement_restrictions')
    op.drop_index(op.f('ix_placement_restrictions_id'), table_name='placement_restrictions')
    op.drop_index(op.f('ix_placement_restrictions_college_id'), table_name='placement_restrictions')
    op.drop_table('placement_restrictions')
    op.drop_index(op.f('ix_student_resumes_student_id'), table_name='student_resumes')
    op.drop_index(op.f('ix_student_resumes_is_deleted'), table_name='student_resumes')
    op.drop_index(op.f('ix_student_resumes_id'), table_name='student_resumes')
    op.drop_index(op.f('ix_student_resumes_college_id'), table_name='student_resumes')
    op.drop_index('ix_student_resume_primary', table_name='student_resumes')
    op.drop_table('student_resumes')
    # ### end Alembic commands ###
