"""hostel_management

Revision ID: 59002adb0ab6
Revises: 5bf979bbba9d
Create Date: 2026-04-14 03:01:39.227100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '59002adb0ab6'
down_revision: Union[str, Sequence[str], None] = '5bf979bbba9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('total_capacity', sa.Integer(), nullable=False),
    sa.Column('grid_rows', sa.Integer(), nullable=False),
    sa.Column('grid_cols', sa.Integer(), nullable=False),
    sa.Column('bed_layout', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_templates_id'), 'room_templates', ['id'], unique=False)
    op.create_index(op.f('ix_room_templates_is_deleted'), 'room_templates', ['is_deleted'], unique=False)
    op.create_table('hostels',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('warden_id', sa.String(), nullable=True),
    sa.Column('total_capacity', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('gender_type', sa.String(), server_default='coed', nullable=False),
    sa.Column('total_floors', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("gender_type IN ('male', 'female', 'coed')", name='ck_hostel_gender'),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warden_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hostel_college_gender', 'hostels', ['college_id', 'gender_type'], unique=False)
    op.create_index(op.f('ix_hostels_id'), 'hostels', ['id'], unique=False)
    op.create_index(op.f('ix_hostels_is_deleted'), 'hostels', ['is_deleted'], unique=False)
    op.create_table('nodal_officer_jurisdictions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nodal_officer_id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['nodal_officer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nodal_officer_id', 'college_id', name='uq_nodal_college')
    )
    op.create_index(op.f('ix_nodal_officer_jurisdictions_college_id'), 'nodal_officer_jurisdictions', ['college_id'], unique=False)
    op.create_index(op.f('ix_nodal_officer_jurisdictions_id'), 'nodal_officer_jurisdictions', ['id'], unique=False)
    op.create_index(op.f('ix_nodal_officer_jurisdictions_is_deleted'), 'nodal_officer_jurisdictions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_nodal_officer_jurisdictions_nodal_officer_id'), 'nodal_officer_jurisdictions', ['nodal_officer_id'], unique=False)
    op.create_table('expert_assignments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('expert_user_id', sa.String(), nullable=False),
    sa.Column('subject_code', sa.String(), nullable=False),
    sa.Column('department_id', sa.String(), nullable=True),
    sa.Column('academic_year', sa.String(), nullable=True),
    sa.Column('assigned_by', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['expert_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('expert_user_id', 'subject_code', 'academic_year', name='uq_expert_subject_year')
    )
    op.create_index('ix_expert_assign_user', 'expert_assignments', ['expert_user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_expert_assignments_college_id'), 'expert_assignments', ['college_id'], unique=False)
    op.create_index(op.f('ix_expert_assignments_expert_user_id'), 'expert_assignments', ['expert_user_id'], unique=False)
    op.create_index(op.f('ix_expert_assignments_id'), 'expert_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_expert_assignments_is_deleted'), 'expert_assignments', ['is_deleted'], unique=False)
    op.create_table('gatepasses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('hostel_id', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('requested_exit', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_return', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_return', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approval_status', sa.String(), server_default='pending', nullable=False),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("approval_status IN ('pending', 'approved', 'rejected', 'expired')", name='ck_gatepass_status'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hostel_id'], ['hostels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_gatepass_hostel_pending', 'gatepasses', ['hostel_id', 'approval_status'], unique=False)
    op.create_index('ix_gatepass_student_status', 'gatepasses', ['student_id', 'approval_status'], unique=False)
    op.create_index(op.f('ix_gatepasses_id'), 'gatepasses', ['id'], unique=False)
    op.create_index(op.f('ix_gatepasses_is_deleted'), 'gatepasses', ['is_deleted'], unique=False)
    op.create_table('rooms',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('hostel_id', sa.String(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=True),
    sa.Column('room_number', sa.String(), nullable=False),
    sa.Column('floor', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('capacity', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hostel_id'], ['hostels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['room_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hostel_id', 'room_number', name='uq_hostel_room_number')
    )
    op.create_index('ix_room_hostel_floor', 'rooms', ['hostel_id', 'floor'], unique=False)
    op.create_index(op.f('ix_rooms_id'), 'rooms', ['id'], unique=False)
    op.create_index(op.f('ix_rooms_is_deleted'), 'rooms', ['is_deleted'], unique=False)
    op.create_table('beds',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('room_id', sa.String(), nullable=False),
    sa.Column('bed_identifier', sa.String(), nullable=False),
    sa.Column('grid_row', sa.Integer(), nullable=False),
    sa.Column('grid_col', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('is_premium', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('selection_fee', sa.Float(), server_default=sa.text('0.0'), nullable=False),
    sa.Column('status', sa.String(), server_default='AVAILABLE', nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('AVAILABLE', 'LOCKED', 'BOOKED', 'MAINTENANCE')", name='ck_bed_status'),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['locked_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'bed_identifier', name='uq_room_bed')
    )
    op.create_index(op.f('ix_beds_id'), 'beds', ['id'], unique=False)
    op.create_index(op.f('ix_beds_is_deleted'), 'beds', ['is_deleted'], unique=False)
    op.create_index('ix_beds_locked_sweep', 'beds', ['locked_at'], unique=False, postgresql_where=sa.text("status = 'LOCKED'"))
    op.create_index('ix_beds_room_status', 'beds', ['room_id', 'status'], unique=False)
    op.create_table('allocations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('bed_id', sa.String(), nullable=False),
    sa.Column('room_id', sa.String(), nullable=False),
    sa.Column('hostel_id', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default='active', nullable=False),
    sa.Column('selection_fee_paid', sa.Float(), server_default=sa.text('0.0'), nullable=False),
    sa.Column('payment_reference', sa.String(), nullable=True),
    sa.Column('allocated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('vacated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bed_id'], ['beds.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hostel_id'], ['hostels.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alloc_hostel_status', 'allocations', ['hostel_id', 'status'], unique=False)
    op.create_index('ix_alloc_student_year', 'allocations', ['student_id', 'academic_year'], unique=False)
    op.create_index(op.f('ix_allocations_id'), 'allocations', ['id'], unique=False)
    op.create_index(op.f('ix_allocations_is_deleted'), 'allocations', ['is_deleted'], unique=False)
    op.add_column('user_profiles', sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'extra_data')
    op.drop_index(op.f('ix_allocations_is_deleted'), table_name='allocations')
    op.drop_index(op.f('ix_allocations_id'), table_name='allocations')
    op.drop_index('ix_alloc_student_year', table_name='allocations')
    op.drop_index('ix_alloc_hostel_status', table_name='allocations')
    op.drop_table('allocations')
    op.drop_index('ix_beds_room_status', table_name='beds')
    op.drop_index('ix_beds_locked_sweep', table_name='beds', postgresql_where=sa.text("status = 'LOCKED'"))
    op.drop_index(op.f('ix_beds_is_deleted'), table_name='beds')
    op.drop_index(op.f('ix_beds_id'), table_name='beds')
    op.drop_table('beds')
    op.drop_index(op.f('ix_rooms_is_deleted'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_id'), table_name='rooms')
    op.drop_index('ix_room_hostel_floor', table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_gatepasses_is_deleted'), table_name='gatepasses')
    op.drop_index(op.f('ix_gatepasses_id'), table_name='gatepasses')
    op.drop_index('ix_gatepass_student_status', table_name='gatepasses')
    op.drop_index('ix_gatepass_hostel_pending', table_name='gatepasses')
    op.drop_table('gatepasses')
    op.drop_index(op.f('ix_expert_assignments_is_deleted'), table_name='expert_assignments')
    op.drop_index(op.f('ix_expert_assignments_id'), table_name='expert_assignments')
    op.drop_index(op.f('ix_expert_assignments_expert_user_id'), table_name='expert_assignments')
    op.drop_index(op.f('ix_expert_assignments_college_id'), table_name='expert_assignments')
    op.drop_index('ix_expert_assign_user', table_name='expert_assignments')
    op.drop_table('expert_assignments')
    op.drop_index(op.f('ix_nodal_officer_jurisdictions_nodal_officer_id'), table_name='nodal_officer_jurisdictions')
    op.drop_index(op.f('ix_nodal_officer_jurisdictions_is_deleted'), table_name='nodal_officer_jurisdictions')
    op.drop_index(op.f('ix_nodal_officer_jurisdictions_id'), table_name='nodal_officer_jurisdictions')
    op.drop_index(op.f('ix_nodal_officer_jurisdictions_college_id'), table_name='nodal_officer_jurisdictions')
    op.drop_table('nodal_officer_jurisdictions')
    op.drop_index(op.f('ix_hostels_is_deleted'), table_name='hostels')
    op.drop_index(op.f('ix_hostels_id'), table_name='hostels')
    op.drop_index('ix_hostel_college_gender', table_name='hostels')
    op.drop_table('hostels')
    op.drop_index(op.f('ix_room_templates_is_deleted'), table_name='room_templates')
    op.drop_index(op.f('ix_room_templates_id'), table_name='room_templates')
    op.drop_table('room_templates')
    # ### end Alembic commands ###
