"""add_interview_warroom_tables

Revision ID: 5bf979bbba9d
Revises: 13a91e6fabcb
Create Date: 2026-04-13 13:00:38.385991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5bf979bbba9d'
down_revision: Union[str, Sequence[str], None] = '13a91e6fabcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mock_interviews',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('interview_type', sa.String(), nullable=False),
    sa.Column('target_role', sa.String(), nullable=True),
    sa.Column('target_company', sa.String(), nullable=True),
    sa.Column('difficulty', sa.String(), server_default='intermediate', nullable=False),
    sa.Column('resume_context', sa.Text(), nullable=True),
    sa.Column('conversation', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('ai_feedback', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), server_default='in_progress', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mock_interviews_college_id'), 'mock_interviews', ['college_id'], unique=False)
    op.create_index(op.f('ix_mock_interviews_id'), 'mock_interviews', ['id'], unique=False)
    op.create_index(op.f('ix_mock_interviews_is_deleted'), 'mock_interviews', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_mock_interviews_student_id'), 'mock_interviews', ['student_id'], unique=False)
    op.create_table('resume_scores',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('parsed_text', sa.Text(), nullable=True),
    sa.Column('ats_score', sa.Float(), nullable=True),
    sa.Column('section_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('keywords_found', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('keywords_missing', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('improvement_tips', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('target_role', sa.String(), nullable=True),
    sa.Column('job_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_scores_college_id'), 'resume_scores', ['college_id'], unique=False)
    op.create_index(op.f('ix_resume_scores_id'), 'resume_scores', ['id'], unique=False)
    op.create_index(op.f('ix_resume_scores_is_deleted'), 'resume_scores', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_resume_scores_student_id'), 'resume_scores', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resume_scores_student_id'), table_name='resume_scores')
    op.drop_index(op.f('ix_resume_scores_is_deleted'), table_name='resume_scores')
    op.drop_index(op.f('ix_resume_scores_id'), table_name='resume_scores')
    op.drop_index(op.f('ix_resume_scores_college_id'), table_name='resume_scores')
    op.drop_table('resume_scores')
    op.drop_index(op.f('ix_mock_interviews_student_id'), table_name='mock_interviews')
    op.drop_index(op.f('ix_mock_interviews_is_deleted'), table_name='mock_interviews')
    op.drop_index(op.f('ix_mock_interviews_id'), table_name='mock_interviews')
    op.drop_index(op.f('ix_mock_interviews_college_id'), table_name='mock_interviews')
    op.drop_table('mock_interviews')
    # ### end Alembic commands ###
