"""Add assessments and CO PO columns

Revision ID: 6ca586af80a7
Revises: 54e44dcc6e76
Create Date: 2026-04-20 23:27:57.625293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6ca586af80a7'
down_revision: Union[str, Sequence[str], None] = '54e44dcc6e76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_generated_assessments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('faculty_id', sa.String(), nullable=False),
    sa.Column('course_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('prompt_used', sa.Text(), nullable=False),
    sa.Column('co_po_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generated_content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['faculty_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_generated_assessments_course_id'), 'ai_generated_assessments', ['course_id'], unique=False)
    op.create_index(op.f('ix_ai_generated_assessments_faculty_id'), 'ai_generated_assessments', ['faculty_id'], unique=False)
    op.create_index(op.f('ix_ai_generated_assessments_id'), 'ai_generated_assessments', ['id'], unique=False)
    op.create_index(op.f('ix_ai_generated_assessments_is_deleted'), 'ai_generated_assessments', ['is_deleted'], unique=False)
    op.create_table('assessment_questions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('assessment_id', sa.String(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(), nullable=False),
    sa.Column('marks', sa.Integer(), nullable=False),
    sa.Column('co_mapped', sa.String(), nullable=True),
    sa.Column('po_mapped', sa.String(), nullable=True),
    sa.Column('bloom_level', sa.String(), nullable=True),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('answer_key', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['ai_generated_assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_questions_assessment_id'), 'assessment_questions', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_assessment_questions_id'), 'assessment_questions', ['id'], unique=False)
    op.create_index(op.f('ix_assessment_questions_is_deleted'), 'assessment_questions', ['is_deleted'], unique=False)
    op.add_column('courses', sa.Column('course_outcomes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('departments', sa.Column('program_outcomes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('placement_applications', sa.Column('application_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('placement_applications', 'application_data')
    op.drop_column('departments', 'program_outcomes')
    op.drop_column('courses', 'course_outcomes')
    op.drop_index(op.f('ix_assessment_questions_is_deleted'), table_name='assessment_questions')
    op.drop_index(op.f('ix_assessment_questions_id'), table_name='assessment_questions')
    op.drop_index(op.f('ix_assessment_questions_assessment_id'), table_name='assessment_questions')
    op.drop_table('assessment_questions')
    op.drop_index(op.f('ix_ai_generated_assessments_is_deleted'), table_name='ai_generated_assessments')
    op.drop_index(op.f('ix_ai_generated_assessments_id'), table_name='ai_generated_assessments')
    op.drop_index(op.f('ix_ai_generated_assessments_faculty_id'), table_name='ai_generated_assessments')
    op.drop_index(op.f('ix_ai_generated_assessments_course_id'), table_name='ai_generated_assessments')
    op.drop_table('ai_generated_assessments')
    # ### end Alembic commands ###
