"""Add Premium Coding Challenges

Revision ID: 6d5104464501
Revises: 2b2ce6699fb9
Create Date: 2026-04-18 10:36:32.221613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d5104464501'
down_revision: Union[str, Sequence[str], None] = '2b2ce6699fb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('premium_coding_challenges',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.Column('constraints', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('topics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('language_support', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('init_code', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('optimal_solution_python', sa.String(), nullable=True),
    sa.Column('test_cases', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('problem_ai_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_live', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_premium_coding_challenges_id'), 'premium_coding_challenges', ['id'], unique=False)
    op.create_index(op.f('ix_premium_coding_challenges_is_deleted'), 'premium_coding_challenges', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_premium_coding_challenges_slug'), 'premium_coding_challenges', ['slug'], unique=True)
    op.create_table('premium_challenge_progress',
    sa.Column('college_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('challenge_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('language_used', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['premium_coding_challenges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_premium_challenge_progress_challenge_id'), 'premium_challenge_progress', ['challenge_id'], unique=False)
    op.create_index(op.f('ix_premium_challenge_progress_college_id'), 'premium_challenge_progress', ['college_id'], unique=False)
    op.create_index(op.f('ix_premium_challenge_progress_id'), 'premium_challenge_progress', ['id'], unique=False)
    op.create_index(op.f('ix_premium_challenge_progress_is_deleted'), 'premium_challenge_progress', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_premium_challenge_progress_student_id'), 'premium_challenge_progress', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_premium_challenge_progress_student_id'), table_name='premium_challenge_progress')
    op.drop_index(op.f('ix_premium_challenge_progress_is_deleted'), table_name='premium_challenge_progress')
    op.drop_index(op.f('ix_premium_challenge_progress_id'), table_name='premium_challenge_progress')
    op.drop_index(op.f('ix_premium_challenge_progress_college_id'), table_name='premium_challenge_progress')
    op.drop_index(op.f('ix_premium_challenge_progress_challenge_id'), table_name='premium_challenge_progress')
    op.drop_table('premium_challenge_progress')
    op.drop_index(op.f('ix_premium_coding_challenges_slug'), table_name='premium_coding_challenges')
    op.drop_index(op.f('ix_premium_coding_challenges_is_deleted'), table_name='premium_coding_challenges')
    op.drop_index(op.f('ix_premium_coding_challenges_id'), table_name='premium_coding_challenges')
    op.drop_table('premium_coding_challenges')
    # ### end Alembic commands ###
