"""Add Nodal Officer models Phase C

Revision ID: 75ca34654a12
Revises: 91226183269c
Create Date: 2026-04-07 01:11:43.403661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '75ca34654a12'
down_revision: Union[str, Sequence[str], None] = '91226183269c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scholarships',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('eligibility_criteria', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scholarships_id'), 'scholarships', ['id'], unique=False)
    op.create_index(op.f('ix_scholarships_is_deleted'), 'scholarships', ['is_deleted'], unique=False)
    op.create_table('scholarship_applications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('scholarship_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scholarship_id'], ['scholarships.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scholarship_applications_id'), 'scholarship_applications', ['id'], unique=False)
    op.create_index(op.f('ix_scholarship_applications_is_deleted'), 'scholarship_applications', ['is_deleted'], unique=False)
    op.create_table('timetable_approvals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('department_id', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timetable_approvals_id'), 'timetable_approvals', ['id'], unique=False)
    op.create_index(op.f('ix_timetable_approvals_is_deleted'), 'timetable_approvals', ['is_deleted'], unique=False)
    op.add_column('courses', sa.Column('college_id', sa.String(), nullable=False))
    op.add_column('courses', sa.Column('subject_code', sa.String(), nullable=False))
    op.add_column('courses', sa.Column('regulation_year', sa.String(), nullable=False))
    op.add_column('courses', sa.Column('hours_per_week', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'courses', 'colleges', ['college_id'], ['id'], ondelete='CASCADE')
    op.add_column('departments', sa.Column('hod_user_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'departments', 'users', ['hod_user_id'], ['id'], ondelete='SET NULL')
    op.add_column('sections', sa.Column('intake', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sections', 'intake')
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.drop_column('departments', 'hod_user_id')
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_column('courses', 'hours_per_week')
    op.drop_column('courses', 'regulation_year')
    op.drop_column('courses', 'subject_code')
    op.drop_column('courses', 'college_id')
    op.drop_index(op.f('ix_timetable_approvals_is_deleted'), table_name='timetable_approvals')
    op.drop_index(op.f('ix_timetable_approvals_id'), table_name='timetable_approvals')
    op.drop_table('timetable_approvals')
    op.drop_index(op.f('ix_scholarship_applications_is_deleted'), table_name='scholarship_applications')
    op.drop_index(op.f('ix_scholarship_applications_id'), table_name='scholarship_applications')
    op.drop_table('scholarship_applications')
    op.drop_index(op.f('ix_scholarships_is_deleted'), table_name='scholarships')
    op.drop_index(op.f('ix_scholarships_id'), table_name='scholarships')
    op.drop_table('scholarships')
    # ### end Alembic commands ###
