"""Phase2 timetable period slots attendance records

Revision ID: 775e87c23103
Revises: 30fdc0b3d569
Create Date: 2026-04-06 10:40:31.967760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '775e87c23103'
down_revision: Union[str, Sequence[str], None] = '30fdc0b3d569'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_calendars',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('working_days', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('events', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_acad_cal_college_year', 'academic_calendars', ['college_id', 'academic_year', 'semester'], unique=False)
    op.create_index(op.f('ix_academic_calendars_id'), 'academic_calendars', ['id'], unique=False)
    op.create_index(op.f('ix_academic_calendars_is_deleted'), 'academic_calendars', ['is_deleted'], unique=False)
    op.create_table('period_slots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('department_id', sa.String(), nullable=False),
    sa.Column('batch', sa.String(), nullable=False),
    sa.Column('section', sa.String(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('day', sa.String(), nullable=False),
    sa.Column('period_no', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(), nullable=False),
    sa.Column('end_time', sa.String(), nullable=False),
    sa.Column('subject_code', sa.String(), nullable=True),
    sa.Column('subject_name', sa.String(), nullable=True),
    sa.Column('faculty_id', sa.String(), nullable=True),
    sa.Column('slot_type', sa.String(), server_default='regular', nullable=False),
    sa.Column('original_faculty_id', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['faculty_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['original_faculty_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_period_slot_batch_day', 'period_slots', ['batch', 'section', 'day', 'academic_year'], unique=False)
    op.create_index('ix_period_slot_college_dept', 'period_slots', ['college_id', 'department_id'], unique=False)
    op.create_index('ix_period_slot_faculty', 'period_slots', ['faculty_id', 'day', 'academic_year'], unique=False)
    op.create_index(op.f('ix_period_slots_id'), 'period_slots', ['id'], unique=False)
    op.create_index(op.f('ix_period_slots_is_deleted'), 'period_slots', ['is_deleted'], unique=False)
    op.create_table('attendance_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('period_slot_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('faculty_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('subject_code', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('marked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_late_entry', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['faculty_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['period_slot_id'], ['period_slots.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'period_slot_id', 'date', name='uq_attendance_entry')
    )
    op.create_index('ix_attendance_faculty_date', 'attendance_records', ['faculty_id', 'date'], unique=False)
    op.create_index(op.f('ix_attendance_records_id'), 'attendance_records', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_records_is_deleted'), 'attendance_records', ['is_deleted'], unique=False)
    op.create_index('ix_attendance_student_subject', 'attendance_records', ['student_id', 'subject_code', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_attendance_student_subject', table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_is_deleted'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_id'), table_name='attendance_records')
    op.drop_index('ix_attendance_faculty_date', table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_index(op.f('ix_period_slots_is_deleted'), table_name='period_slots')
    op.drop_index(op.f('ix_period_slots_id'), table_name='period_slots')
    op.drop_index('ix_period_slot_faculty', table_name='period_slots')
    op.drop_index('ix_period_slot_college_dept', table_name='period_slots')
    op.drop_index('ix_period_slot_batch_day', table_name='period_slots')
    op.drop_table('period_slots')
    op.drop_index(op.f('ix_academic_calendars_is_deleted'), table_name='academic_calendars')
    op.drop_index(op.f('ix_academic_calendars_id'), table_name='academic_calendars')
    op.drop_index('ix_acad_cal_college_year', table_name='academic_calendars')
    op.drop_table('academic_calendars')
    # ### end Alembic commands ###
