"""accreditation_models

Revision ID: 79df38512280
Revises: 2d76721ba7fa
Create Date: 2026-04-24 15:17:04.127959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '79df38512280'
down_revision: Union[str, Sequence[str], None] = '2d76721ba7fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.
    
    KNOWN LIMITATION: 
    The calculate_co_attainment service resolves scope via subject_code rather than a direct 
    course_id foreign key on MarkSubmission. That means if two different courses in the 
    college share the same subject_code (which can happen with electives or cross-listed courses), 
    submissions from both will bleed into each other's CO attainment. This is a pre-existing 
    data model constraint. If a course_id FK is added to MarkSubmission later, update the 
    attainment_service to scope by course_id directly to resolve this.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accreditation_evidence',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('criterion_id', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('s3_key', sa.String(), nullable=False),
    sa.Column('hash_checksum', sa.String(), nullable=False),
    sa.Column('uploaded_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_accreditation_evidence_college_criterion', 'accreditation_evidence', ['college_id', 'criterion_id'], unique=False)
    op.create_index(op.f('ix_accreditation_evidence_college_id'), 'accreditation_evidence', ['college_id'], unique=False)
    op.create_index(op.f('ix_accreditation_evidence_id'), 'accreditation_evidence', ['id'], unique=False)
    op.create_index(op.f('ix_accreditation_evidence_is_deleted'), 'accreditation_evidence', ['is_deleted'], unique=False)
    op.create_table('faculty_achievements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('faculty_id', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('FDP', 'Workshop', 'Publication', 'Patent', 'Award', 'Consultancy', 'STTP', 'Conference', name='faculty_achievement_type_enum'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('issuer', sa.String(), nullable=True),
    sa.Column('impact_factor', sa.Float(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('evidence_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['faculty_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_faculty_achievement_college_faculty', 'faculty_achievements', ['college_id', 'faculty_id'], unique=False)
    op.create_index(op.f('ix_faculty_achievements_college_id'), 'faculty_achievements', ['college_id'], unique=False)
    op.create_index(op.f('ix_faculty_achievements_id'), 'faculty_achievements', ['id'], unique=False)
    op.create_index(op.f('ix_faculty_achievements_is_deleted'), 'faculty_achievements', ['is_deleted'], unique=False)
    op.create_table('faculty_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('faculty_id', sa.String(), nullable=False),
    sa.Column('qualification', sa.String(), nullable=True),
    sa.Column('specialization', sa.String(), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('joining_date', sa.Date(), nullable=True),
    sa.Column('designation', sa.String(), nullable=True),
    sa.Column('h_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['faculty_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('faculty_id')
    )
    op.create_index('ix_faculty_profile_college', 'faculty_profiles', ['college_id'], unique=False)
    op.create_index(op.f('ix_faculty_profiles_college_id'), 'faculty_profiles', ['college_id'], unique=False)
    op.create_index(op.f('ix_faculty_profiles_id'), 'faculty_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_faculty_profiles_is_deleted'), 'faculty_profiles', ['is_deleted'], unique=False)
    op.create_table('naac_audit_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('criterion', sa.Integer(), nullable=False),
    sa.Column('metric_code', sa.String(), nullable=False),
    sa.Column('computed_value', sa.Float(), nullable=True),
    sa.Column('evidence_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('criterion >= 1 AND criterion <= 7', name='ck_criterion_range'),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['locked_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('college_id', 'academic_year', 'metric_code', name='uq_naac_snapshot')
    )
    op.create_index(op.f('ix_naac_audit_snapshots_college_id'), 'naac_audit_snapshots', ['college_id'], unique=False)
    op.create_index(op.f('ix_naac_audit_snapshots_id'), 'naac_audit_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_naac_audit_snapshots_is_deleted'), 'naac_audit_snapshots', ['is_deleted'], unique=False)
    op.create_index('ix_naac_snapshot_college_year', 'naac_audit_snapshots', ['college_id', 'academic_year'], unique=False)
    op.create_table('grievance_actions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('grievance_id', sa.String(), nullable=False),
    sa.Column('actioned_by', sa.String(), nullable=True),
    sa.Column('action_taken', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actioned_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['grievance_id'], ['grievances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_grievance_action_college_grievance', 'grievance_actions', ['college_id', 'grievance_id'], unique=False)
    op.create_index(op.f('ix_grievance_actions_college_id'), 'grievance_actions', ['college_id'], unique=False)
    op.create_index(op.f('ix_grievance_actions_id'), 'grievance_actions', ['id'], unique=False)
    op.create_index(op.f('ix_grievance_actions_is_deleted'), 'grievance_actions', ['is_deleted'], unique=False)
    op.create_table('program_specific_outcomes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('department_id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_id', 'code', name='uq_dept_pso_code')
    )
    op.create_index(op.f('ix_program_specific_outcomes_college_id'), 'program_specific_outcomes', ['college_id'], unique=False)
    op.create_index(op.f('ix_program_specific_outcomes_id'), 'program_specific_outcomes', ['id'], unique=False)
    op.create_index(op.f('ix_program_specific_outcomes_is_deleted'), 'program_specific_outcomes', ['is_deleted'], unique=False)
    op.create_index('ix_pso_college_dept', 'program_specific_outcomes', ['college_id', 'department_id'], unique=False)
    op.create_table('course_exit_surveys',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('course_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('co_ratings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('overall_rating', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'student_id', 'academic_year', name='uq_exit_survey')
    )
    op.create_index(op.f('ix_course_exit_surveys_college_id'), 'course_exit_surveys', ['college_id'], unique=False)
    op.create_index(op.f('ix_course_exit_surveys_id'), 'course_exit_surveys', ['id'], unique=False)
    op.create_index(op.f('ix_course_exit_surveys_is_deleted'), 'course_exit_surveys', ['is_deleted'], unique=False)
    op.create_index('ix_exit_survey_course_year', 'course_exit_surveys', ['course_id', 'academic_year'], unique=False)
    op.create_table('po_attainment_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('po_id', sa.String(), nullable=False),
    sa.Column('department_id', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('attainment_value', sa.Float(), nullable=True),
    sa.Column('calculation_method', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['locked_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['po_id'], ['program_outcomes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('po_id', 'department_id', 'academic_year', name='uq_po_attainment')
    )
    op.create_index('ix_po_attainment_college_year', 'po_attainment_records', ['college_id', 'academic_year'], unique=False)
    op.create_index(op.f('ix_po_attainment_records_college_id'), 'po_attainment_records', ['college_id'], unique=False)
    op.create_index(op.f('ix_po_attainment_records_id'), 'po_attainment_records', ['id'], unique=False)
    op.create_index(op.f('ix_po_attainment_records_is_deleted'), 'po_attainment_records', ['is_deleted'], unique=False)
    op.create_table('pso_attainment_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('pso_id', sa.String(), nullable=False),
    sa.Column('department_id', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('attainment_value', sa.Float(), nullable=True),
    sa.Column('calculation_method', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['locked_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pso_id'], ['program_specific_outcomes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pso_id', 'department_id', 'academic_year', name='uq_pso_attainment')
    )
    op.create_index(op.f('ix_pso_attainment_records_college_id'), 'pso_attainment_records', ['college_id'], unique=False)
    op.create_index(op.f('ix_pso_attainment_records_id'), 'pso_attainment_records', ['id'], unique=False)
    op.create_index(op.f('ix_pso_attainment_records_is_deleted'), 'pso_attainment_records', ['is_deleted'], unique=False)
    op.create_table('co_attainment_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('co_id', sa.String(), nullable=False),
    sa.Column('course_id', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('direct_attainment', sa.Float(), nullable=True),
    sa.Column('indirect_attainment', sa.Float(), nullable=True),
    sa.Column('final_attainment', sa.Float(), nullable=True),
    sa.Column('threshold', sa.Float(), server_default=sa.text('60.0'), nullable=False),
    sa.Column('is_attained', sa.Boolean(), nullable=True),
    sa.Column('calculation_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['co_id'], ['course_outcomes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['locked_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('co_id', 'course_id', 'academic_year', name='uq_co_attainment')
    )
    op.create_index('ix_co_attainment_college_year', 'co_attainment_records', ['college_id', 'academic_year'], unique=False)
    op.create_index(op.f('ix_co_attainment_records_college_id'), 'co_attainment_records', ['college_id'], unique=False)
    op.create_index(op.f('ix_co_attainment_records_id'), 'co_attainment_records', ['id'], unique=False)
    op.create_index(op.f('ix_co_attainment_records_is_deleted'), 'co_attainment_records', ['is_deleted'], unique=False)
    op.create_table('co_pso_mappings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('co_id', sa.String(), nullable=False),
    sa.Column('pso_id', sa.String(), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('rationale', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['co_id'], ['course_outcomes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pso_id'], ['program_specific_outcomes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('co_id', 'pso_id', name='uq_co_pso_mapping')
    )
    op.create_index(op.f('ix_co_pso_mappings_id'), 'co_pso_mappings', ['id'], unique=False)
    op.create_index(op.f('ix_co_pso_mappings_is_deleted'), 'co_pso_mappings', ['is_deleted'], unique=False)
    # Explicitly create coursecategoryenum in postgres
    course_category_enum = postgresql.ENUM('core', 'elective', 'multidisciplinary', 'open_elective', 'vsc', 'sec', 'aec', 'mdc', name='coursecategoryenum')
    course_category_enum.create(op.get_bind())

    op.add_column('co_po_mappings', sa.Column('rationale', sa.String(), nullable=True))
    op.add_column('co_po_mappings', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('courses', sa.Column('course_category', course_category_enum, server_default='core', nullable=False))
    op.add_column('courses', sa.Column('lecture_hrs', sa.Integer(), nullable=True))
    op.add_column('courses', sa.Column('tutorial_hrs', sa.Integer(), nullable=True))
    op.add_column('courses', sa.Column('practical_hrs', sa.Integer(), nullable=True))
    op.add_column('courses', sa.Column('is_mooc', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('courses', sa.Column('mooc_platform', sa.String(), nullable=True))
    op.add_column('courses', sa.Column('mooc_credit_equiv', sa.Integer(), nullable=True))
    op.add_column('grievances', sa.Column('is_anonymous', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('mark_submission_entries', sa.Column('co_wise_marks', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('mark_submissions', sa.Column('co_ids', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True))
    op.add_column('program_outcomes', sa.Column('college_id', sa.String(), nullable=True))
    op.create_index('ix_po_college_dept', 'program_outcomes', ['college_id', 'department_id'], unique=False)
    op.create_index(op.f('ix_program_outcomes_college_id'), 'program_outcomes', ['college_id'], unique=False)
    op.create_foreign_key(None, 'program_outcomes', 'colleges', ['college_id'], ['id'], ondelete='CASCADE')
    op.add_column('user_profiles', sa.Column('abc_id', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('enrollment_status', sa.String(), server_default='active', nullable=False))
    op.create_index(op.f('ix_user_profiles_abc_id'), 'user_profiles', ['abc_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profiles_abc_id'), table_name='user_profiles')
    op.drop_column('user_profiles', 'enrollment_status')
    op.drop_column('user_profiles', 'abc_id')
    op.drop_constraint(None, 'program_outcomes', type_='foreignkey')
    op.drop_index(op.f('ix_program_outcomes_college_id'), table_name='program_outcomes')
    op.drop_index('ix_po_college_dept', table_name='program_outcomes')
    op.drop_column('program_outcomes', 'college_id')
    op.drop_column('mark_submissions', 'co_ids')
    op.drop_column('mark_submission_entries', 'co_wise_marks')
    op.drop_column('grievances', 'is_anonymous')
    op.drop_column('courses', 'mooc_credit_equiv')
    op.drop_column('courses', 'mooc_platform')
    op.drop_column('courses', 'is_mooc')
    op.drop_column('courses', 'practical_hrs')
    op.drop_column('courses', 'tutorial_hrs')
    op.drop_column('courses', 'lecture_hrs')
    op.drop_column('courses', 'course_category')
    op.drop_column('co_po_mappings', 'is_active')
    op.drop_column('co_po_mappings', 'rationale')
    op.drop_index(op.f('ix_co_pso_mappings_is_deleted'), table_name='co_pso_mappings')
    op.drop_index(op.f('ix_co_pso_mappings_id'), table_name='co_pso_mappings')
    op.drop_table('co_pso_mappings')
    op.drop_index(op.f('ix_co_attainment_records_is_deleted'), table_name='co_attainment_records')
    op.drop_index(op.f('ix_co_attainment_records_id'), table_name='co_attainment_records')
    op.drop_index(op.f('ix_co_attainment_records_college_id'), table_name='co_attainment_records')
    op.drop_index('ix_co_attainment_college_year', table_name='co_attainment_records')
    op.drop_table('co_attainment_records')
    op.drop_index(op.f('ix_pso_attainment_records_is_deleted'), table_name='pso_attainment_records')
    op.drop_index(op.f('ix_pso_attainment_records_id'), table_name='pso_attainment_records')
    op.drop_index(op.f('ix_pso_attainment_records_college_id'), table_name='pso_attainment_records')
    op.drop_table('pso_attainment_records')
    op.drop_index(op.f('ix_po_attainment_records_is_deleted'), table_name='po_attainment_records')
    op.drop_index(op.f('ix_po_attainment_records_id'), table_name='po_attainment_records')
    op.drop_index(op.f('ix_po_attainment_records_college_id'), table_name='po_attainment_records')
    op.drop_index('ix_po_attainment_college_year', table_name='po_attainment_records')
    op.drop_table('po_attainment_records')
    op.drop_index('ix_exit_survey_course_year', table_name='course_exit_surveys')
    op.drop_index(op.f('ix_course_exit_surveys_is_deleted'), table_name='course_exit_surveys')
    op.drop_index(op.f('ix_course_exit_surveys_id'), table_name='course_exit_surveys')
    op.drop_index(op.f('ix_course_exit_surveys_college_id'), table_name='course_exit_surveys')
    op.drop_table('course_exit_surveys')
    op.drop_index('ix_pso_college_dept', table_name='program_specific_outcomes')
    op.drop_index(op.f('ix_program_specific_outcomes_is_deleted'), table_name='program_specific_outcomes')
    op.drop_index(op.f('ix_program_specific_outcomes_id'), table_name='program_specific_outcomes')
    op.drop_index(op.f('ix_program_specific_outcomes_college_id'), table_name='program_specific_outcomes')
    op.drop_table('program_specific_outcomes')
    op.drop_index(op.f('ix_grievance_actions_is_deleted'), table_name='grievance_actions')
    op.drop_index(op.f('ix_grievance_actions_id'), table_name='grievance_actions')
    op.drop_index(op.f('ix_grievance_actions_college_id'), table_name='grievance_actions')
    op.drop_index('ix_grievance_action_college_grievance', table_name='grievance_actions')
    op.drop_table('grievance_actions')
    op.drop_index('ix_naac_snapshot_college_year', table_name='naac_audit_snapshots')
    op.drop_index(op.f('ix_naac_audit_snapshots_is_deleted'), table_name='naac_audit_snapshots')
    op.drop_index(op.f('ix_naac_audit_snapshots_id'), table_name='naac_audit_snapshots')
    op.drop_index(op.f('ix_naac_audit_snapshots_college_id'), table_name='naac_audit_snapshots')
    op.drop_table('naac_audit_snapshots')
    op.drop_index(op.f('ix_faculty_profiles_is_deleted'), table_name='faculty_profiles')
    op.drop_index(op.f('ix_faculty_profiles_id'), table_name='faculty_profiles')
    op.drop_index(op.f('ix_faculty_profiles_college_id'), table_name='faculty_profiles')
    op.drop_index('ix_faculty_profile_college', table_name='faculty_profiles')
    op.drop_table('faculty_profiles')
    op.drop_index(op.f('ix_faculty_achievements_is_deleted'), table_name='faculty_achievements')
    op.drop_index(op.f('ix_faculty_achievements_id'), table_name='faculty_achievements')
    op.drop_index(op.f('ix_faculty_achievements_college_id'), table_name='faculty_achievements')
    op.drop_index('ix_faculty_achievement_college_faculty', table_name='faculty_achievements')
    op.drop_table('faculty_achievements')
    op.drop_index(op.f('ix_accreditation_evidence_is_deleted'), table_name='accreditation_evidence')
    op.drop_index(op.f('ix_accreditation_evidence_id'), table_name='accreditation_evidence')
    op.drop_index(op.f('ix_accreditation_evidence_college_id'), table_name='accreditation_evidence')
    op.drop_index('ix_accreditation_evidence_college_criterion', table_name='accreditation_evidence')
    op.drop_table('accreditation_evidence')
    # ### end Alembic commands ###
