"""phase6_teaching_records

Revision ID: 79f332346d68
Revises: e80419ea537f
Create Date: 2026-04-06 14:30:53.458207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79f332346d68'
down_revision: Union[str, Sequence[str], None] = 'e80419ea537f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teaching_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('faculty_id', sa.String(), nullable=False),
    sa.Column('period_slot_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('planned_topic', sa.String(), nullable=True),
    sa.Column('actual_topic', sa.String(), nullable=True),
    sa.Column('methodology', sa.String(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('is_class_record_submitted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['faculty_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['period_slot_id'], ['period_slots.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('faculty_id', 'period_slot_id', 'date', name='uq_teaching_record')
    )
    op.create_index('ix_teaching_record_faculty_date', 'teaching_records', ['faculty_id', 'date'], unique=False)
    op.create_index(op.f('ix_teaching_records_id'), 'teaching_records', ['id'], unique=False)
    op.create_index(op.f('ix_teaching_records_is_deleted'), 'teaching_records', ['is_deleted'], unique=False)
    op.drop_constraint(op.f('subject_cia_configs_template_id_fkey'), 'subject_cia_configs', type_='foreignkey')
    op.create_foreign_key(None, 'subject_cia_configs', 'cia_templates', ['template_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subject_cia_configs', type_='foreignkey')
    op.create_foreign_key(op.f('subject_cia_configs_template_id_fkey'), 'subject_cia_configs', 'cia_templates', ['template_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_teaching_records_is_deleted'), table_name='teaching_records')
    op.drop_index(op.f('ix_teaching_records_id'), table_name='teaching_records')
    op.drop_index('ix_teaching_record_faculty_date', table_name='teaching_records')
    op.drop_table('teaching_records')
    # ### end Alembic commands ###
