"""hod_dashboard_phase2_assignments_progression

Revision ID: 83deaee2758a
Revises: 79f332346d68
Create Date: 2026-04-06 18:58:17.156477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '83deaee2758a'
down_revision: Union[str, Sequence[str], None] = '79f332346d68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_in_charges',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('faculty_id', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('batch', sa.String(), nullable=False),
    sa.Column('section', sa.String(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['faculty_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('faculty_id', 'department', 'batch', 'section', 'semester', 'academic_year', name='uq_class_in_charge')
    )
    op.create_index('ix_cic_dept_batch_sec', 'class_in_charges', ['department', 'batch', 'section', 'academic_year'], unique=False)
    op.create_index(op.f('ix_class_in_charges_id'), 'class_in_charges', ['id'], unique=False)
    op.create_index(op.f('ix_class_in_charges_is_deleted'), 'class_in_charges', ['is_deleted'], unique=False)
    op.create_table('mentor_assignments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('faculty_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['faculty_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mentor_assignments_id'), 'mentor_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_mentor_assignments_is_deleted'), 'mentor_assignments', ['is_deleted'], unique=False)
    op.create_index('ix_mentor_student_year_active', 'mentor_assignments', ['student_id', 'academic_year'], unique=True, postgresql_where=sa.text('is_active = true'))
    op.create_table('student_progressions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('progression_type', sa.String(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_progression_student_type', 'student_progressions', ['student_id', 'progression_type'], unique=False)
    op.create_index(op.f('ix_student_progressions_id'), 'student_progressions', ['id'], unique=False)
    op.create_index(op.f('ix_student_progressions_is_deleted'), 'student_progressions', ['is_deleted'], unique=False)
    op.add_column('attendance_records', sa.Column('source', sa.String(), server_default='faculty_manual', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance_records', 'source')
    op.drop_index(op.f('ix_student_progressions_is_deleted'), table_name='student_progressions')
    op.drop_index(op.f('ix_student_progressions_id'), table_name='student_progressions')
    op.drop_index('ix_progression_student_type', table_name='student_progressions')
    op.drop_table('student_progressions')
    op.drop_index('ix_mentor_student_year_active', table_name='mentor_assignments', postgresql_where=sa.text('is_active = true'))
    op.drop_index(op.f('ix_mentor_assignments_is_deleted'), table_name='mentor_assignments')
    op.drop_index(op.f('ix_mentor_assignments_id'), table_name='mentor_assignments')
    op.drop_table('mentor_assignments')
    op.drop_index(op.f('ix_class_in_charges_is_deleted'), table_name='class_in_charges')
    op.drop_index(op.f('ix_class_in_charges_id'), table_name='class_in_charges')
    op.drop_index('ix_cic_dept_batch_sec', table_name='class_in_charges')
    op.drop_table('class_in_charges')
    # ### end Alembic commands ###
