"""rename_celery_to_arq

Revision ID: 868b548e7015
Revises: 0392bb4deeac
Create Date: 2026-05-09 15:11:02.218930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '868b548e7015'
down_revision: Union[str, Sequence[str], None] = '0392bb4deeac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accreditation_report_jobs', sa.Column('arq_job_id', sa.String(), nullable=True))
    op.drop_column('accreditation_report_jobs', 'celery_task_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accreditation_report_jobs', sa.Column('celery_task_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('accreditation_report_jobs', 'arq_job_id')
    # ### end Alembic commands ###
