"""phase8_naac_compliance

Revision ID: 91226183269c
Revises: aa73d849728b
Create Date: 2026-04-07 00:07:43.549009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '91226183269c'
down_revision: Union[str, Sequence[str], None] = 'aa73d849728b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fee_templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('fee_type', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_templates_college_id'), 'fee_templates', ['college_id'], unique=False)
    op.create_index(op.f('ix_fee_templates_id'), 'fee_templates', ['id'], unique=False)
    op.create_index(op.f('ix_fee_templates_is_deleted'), 'fee_templates', ['is_deleted'], unique=False)
    op.create_table('activity_permissions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('faculty_id', sa.String(), nullable=False),
    sa.Column('activity_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('venue', sa.String(), nullable=True),
    sa.Column('phase', sa.String(), server_default='pre_event', nullable=False),
    sa.Column('status', sa.String(), server_default='pending', nullable=False),
    sa.Column('hod_approved_by', sa.String(), nullable=True),
    sa.Column('report_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['faculty_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hod_approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_permissions_college_id'), 'activity_permissions', ['college_id'], unique=False)
    op.create_index(op.f('ix_activity_permissions_faculty_id'), 'activity_permissions', ['faculty_id'], unique=False)
    op.create_index(op.f('ix_activity_permissions_id'), 'activity_permissions', ['id'], unique=False)
    op.create_index(op.f('ix_activity_permissions_is_deleted'), 'activity_permissions', ['is_deleted'], unique=False)
    op.create_table('department_meetings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('department_id', sa.String(), nullable=False),
    sa.Column('organizer_id', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('agenda', sa.String(), nullable=False),
    sa.Column('minutes', sa.String(), nullable=True),
    sa.Column('attendance_record', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organizer_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_department_meetings_college_id'), 'department_meetings', ['college_id'], unique=False)
    op.create_index(op.f('ix_department_meetings_department_id'), 'department_meetings', ['department_id'], unique=False)
    op.create_index(op.f('ix_department_meetings_id'), 'department_meetings', ['id'], unique=False)
    op.create_index(op.f('ix_department_meetings_is_deleted'), 'department_meetings', ['is_deleted'], unique=False)
    op.create_table('fee_payments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('fee_template_id', sa.String(), nullable=False),
    sa.Column('amount_paid', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('transaction_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transaction_reference', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fee_template_id'], ['fee_templates.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_payments_college_id'), 'fee_payments', ['college_id'], unique=False)
    op.create_index(op.f('ix_fee_payments_id'), 'fee_payments', ['id'], unique=False)
    op.create_index(op.f('ix_fee_payments_is_deleted'), 'fee_payments', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_fee_payments_student_id'), 'fee_payments', ['student_id'], unique=False)
    op.create_table('out_of_campus_permissions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('faculty_id', sa.String(), nullable=False),
    sa.Column('destination', sa.String(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('departure_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('return_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), server_default='pending', nullable=False),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['faculty_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_out_of_campus_permissions_college_id'), 'out_of_campus_permissions', ['college_id'], unique=False)
    op.create_index(op.f('ix_out_of_campus_permissions_faculty_id'), 'out_of_campus_permissions', ['faculty_id'], unique=False)
    op.create_index(op.f('ix_out_of_campus_permissions_id'), 'out_of_campus_permissions', ['id'], unique=False)
    op.create_index(op.f('ix_out_of_campus_permissions_is_deleted'), 'out_of_campus_permissions', ['is_deleted'], unique=False)
    op.create_table('task_assignments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('assigner_id', sa.String(), nullable=True),
    sa.Column('assignee_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=False),
    sa.Column('priority', sa.String(), server_default='medium', nullable=False),
    sa.Column('status', sa.String(), server_default='pending', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assigner_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_assignments_assignee_id'), 'task_assignments', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_task_assignments_college_id'), 'task_assignments', ['college_id'], unique=False)
    op.create_index(op.f('ix_task_assignments_id'), 'task_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_task_assignments_is_deleted'), 'task_assignments', ['is_deleted'], unique=False)
    op.create_table('free_period_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('faculty_id', sa.String(), nullable=False),
    sa.Column('period_slot_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default='pending', nullable=False),
    sa.Column('processed_by', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['faculty_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['period_slot_id'], ['period_slots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['processed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_free_period_requests_college_id'), 'free_period_requests', ['college_id'], unique=False)
    op.create_index(op.f('ix_free_period_requests_faculty_id'), 'free_period_requests', ['faculty_id'], unique=False)
    op.create_index(op.f('ix_free_period_requests_id'), 'free_period_requests', ['id'], unique=False)
    op.create_index(op.f('ix_free_period_requests_is_deleted'), 'free_period_requests', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_free_period_requests_is_deleted'), table_name='free_period_requests')
    op.drop_index(op.f('ix_free_period_requests_id'), table_name='free_period_requests')
    op.drop_index(op.f('ix_free_period_requests_faculty_id'), table_name='free_period_requests')
    op.drop_index(op.f('ix_free_period_requests_college_id'), table_name='free_period_requests')
    op.drop_table('free_period_requests')
    op.drop_index(op.f('ix_task_assignments_is_deleted'), table_name='task_assignments')
    op.drop_index(op.f('ix_task_assignments_id'), table_name='task_assignments')
    op.drop_index(op.f('ix_task_assignments_college_id'), table_name='task_assignments')
    op.drop_index(op.f('ix_task_assignments_assignee_id'), table_name='task_assignments')
    op.drop_table('task_assignments')
    op.drop_index(op.f('ix_out_of_campus_permissions_is_deleted'), table_name='out_of_campus_permissions')
    op.drop_index(op.f('ix_out_of_campus_permissions_id'), table_name='out_of_campus_permissions')
    op.drop_index(op.f('ix_out_of_campus_permissions_faculty_id'), table_name='out_of_campus_permissions')
    op.drop_index(op.f('ix_out_of_campus_permissions_college_id'), table_name='out_of_campus_permissions')
    op.drop_table('out_of_campus_permissions')
    op.drop_index(op.f('ix_fee_payments_student_id'), table_name='fee_payments')
    op.drop_index(op.f('ix_fee_payments_is_deleted'), table_name='fee_payments')
    op.drop_index(op.f('ix_fee_payments_id'), table_name='fee_payments')
    op.drop_index(op.f('ix_fee_payments_college_id'), table_name='fee_payments')
    op.drop_table('fee_payments')
    op.drop_index(op.f('ix_department_meetings_is_deleted'), table_name='department_meetings')
    op.drop_index(op.f('ix_department_meetings_id'), table_name='department_meetings')
    op.drop_index(op.f('ix_department_meetings_department_id'), table_name='department_meetings')
    op.drop_index(op.f('ix_department_meetings_college_id'), table_name='department_meetings')
    op.drop_table('department_meetings')
    op.drop_index(op.f('ix_activity_permissions_is_deleted'), table_name='activity_permissions')
    op.drop_index(op.f('ix_activity_permissions_id'), table_name='activity_permissions')
    op.drop_index(op.f('ix_activity_permissions_faculty_id'), table_name='activity_permissions')
    op.drop_index(op.f('ix_activity_permissions_college_id'), table_name='activity_permissions')
    op.drop_table('activity_permissions')
    op.drop_index(op.f('ix_fee_templates_is_deleted'), table_name='fee_templates')
    op.drop_index(op.f('ix_fee_templates_id'), table_name='fee_templates')
    op.drop_index(op.f('ix_fee_templates_college_id'), table_name='fee_templates')
    op.drop_table('fee_templates')
    # ### end Alembic commands ###
