"""Add role to PinnedInsight

Revision ID: 9cd916385158
Revises: e3cbdf360837
Create Date: 2026-04-17 04:31:04.382343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cd916385158'
down_revision: Union[str, Sequence[str], None] = 'e3cbdf360837'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pinned_insights', sa.Column('role', sa.String(), server_default='PRINCIPAL', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pinned_insights', 'role')
    # ### end Alembic commands ###
