"""Add Retired Faculty Models

Revision ID: a3c7fe8042b6
Revises: b5f5c86d99da
Create Date: 2026-04-07 22:00:57.358903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a3c7fe8042b6'
down_revision: Union[str, Sequence[str], None] = 'b5f5c86d99da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultancy_engagements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('retired_faculty_id', sa.String(), nullable=False),
    sa.Column('client_organization', sa.String(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('fee_amount', sa.Float(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['retired_faculty_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultancy_engagements_college_id'), 'consultancy_engagements', ['college_id'], unique=False)
    op.create_index(op.f('ix_consultancy_engagements_id'), 'consultancy_engagements', ['id'], unique=False)
    op.create_index(op.f('ix_consultancy_engagements_is_deleted'), 'consultancy_engagements', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_consultancy_engagements_retired_faculty_id'), 'consultancy_engagements', ['retired_faculty_id'], unique=False)
    op.create_table('retired_faculty_advisory',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('retired_faculty_id', sa.String(), nullable=False),
    sa.Column('role_type', sa.String(), nullable=False),
    sa.Column('scope_description', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('appointed_by', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['appointed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['retired_faculty_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retired_faculty_advisory_college_id'), 'retired_faculty_advisory', ['college_id'], unique=False)
    op.create_index(op.f('ix_retired_faculty_advisory_id'), 'retired_faculty_advisory', ['id'], unique=False)
    op.create_index(op.f('ix_retired_faculty_advisory_is_deleted'), 'retired_faculty_advisory', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_retired_faculty_advisory_retired_faculty_id'), 'retired_faculty_advisory', ['retired_faculty_id'], unique=False)
    op.create_table('retired_faculty_research',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('retired_faculty_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('funding_agency', sa.String(), nullable=True),
    sa.Column('co_investigators', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), server_default='ongoing', nullable=False),
    sa.Column('grant_amount', sa.Float(), nullable=True),
    sa.Column('publication_urls', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['retired_faculty_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retired_faculty_research_college_id'), 'retired_faculty_research', ['college_id'], unique=False)
    op.create_index(op.f('ix_retired_faculty_research_id'), 'retired_faculty_research', ['id'], unique=False)
    op.create_index(op.f('ix_retired_faculty_research_is_deleted'), 'retired_faculty_research', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_retired_faculty_research_retired_faculty_id'), 'retired_faculty_research', ['retired_faculty_id'], unique=False)
    op.add_column('alumni_guest_lectures', sa.Column('lecturer_id', sa.String(), nullable=False))
    op.add_column('alumni_guest_lectures', sa.Column('source_type', sa.String(), server_default='alumni', nullable=False))
    op.drop_index(op.f('ix_alumni_guest_lectures_alumni_id'), table_name='alumni_guest_lectures')
    op.create_index(op.f('ix_alumni_guest_lectures_lecturer_id'), 'alumni_guest_lectures', ['lecturer_id'], unique=False)
    op.drop_constraint(op.f('alumni_guest_lectures_alumni_id_fkey'), 'alumni_guest_lectures', type_='foreignkey')
    op.create_foreign_key(None, 'alumni_guest_lectures', 'users', ['lecturer_id'], ['id'], ondelete='CASCADE')
    op.drop_column('alumni_guest_lectures', 'alumni_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alumni_guest_lectures', sa.Column('alumni_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'alumni_guest_lectures', type_='foreignkey')
    op.create_foreign_key(op.f('alumni_guest_lectures_alumni_id_fkey'), 'alumni_guest_lectures', 'users', ['alumni_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_alumni_guest_lectures_lecturer_id'), table_name='alumni_guest_lectures')
    op.create_index(op.f('ix_alumni_guest_lectures_alumni_id'), 'alumni_guest_lectures', ['alumni_id'], unique=False)
    op.drop_column('alumni_guest_lectures', 'source_type')
    op.drop_column('alumni_guest_lectures', 'lecturer_id')
    op.drop_index(op.f('ix_retired_faculty_research_retired_faculty_id'), table_name='retired_faculty_research')
    op.drop_index(op.f('ix_retired_faculty_research_is_deleted'), table_name='retired_faculty_research')
    op.drop_index(op.f('ix_retired_faculty_research_id'), table_name='retired_faculty_research')
    op.drop_index(op.f('ix_retired_faculty_research_college_id'), table_name='retired_faculty_research')
    op.drop_table('retired_faculty_research')
    op.drop_index(op.f('ix_retired_faculty_advisory_retired_faculty_id'), table_name='retired_faculty_advisory')
    op.drop_index(op.f('ix_retired_faculty_advisory_is_deleted'), table_name='retired_faculty_advisory')
    op.drop_index(op.f('ix_retired_faculty_advisory_id'), table_name='retired_faculty_advisory')
    op.drop_index(op.f('ix_retired_faculty_advisory_college_id'), table_name='retired_faculty_advisory')
    op.drop_table('retired_faculty_advisory')
    op.drop_index(op.f('ix_consultancy_engagements_retired_faculty_id'), table_name='consultancy_engagements')
    op.drop_index(op.f('ix_consultancy_engagements_is_deleted'), table_name='consultancy_engagements')
    op.drop_index(op.f('ix_consultancy_engagements_id'), table_name='consultancy_engagements')
    op.drop_index(op.f('ix_consultancy_engagements_college_id'), table_name='consultancy_engagements')
    op.drop_table('consultancy_engagements')
    # ### end Alembic commands ###
