"""add_admissions_and_college_modules_and_allocation_updates

Revision ID: ab11286fb520
Revises: b7f8e9a0c1d2
Create Date: 2026-04-17 18:28:23.856080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab11286fb520'
down_revision: Union[str, Sequence[str], None] = 'b7f8e9a0c1d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admissions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('admission_number', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('mobile_number', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('branch', sa.String(), nullable=False),
    sa.Column('batch', sa.String(), nullable=False),
    sa.Column('quota', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('otp_hash', sa.String(), nullable=True),
    sa.Column('otp_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('college_id', 'admission_number', name='uq_admission_college')
    )
    op.create_index('ix_admission_mobile', 'admissions', ['mobile_number', 'college_id'], unique=False)
    op.create_index(op.f('ix_admissions_is_deleted'), 'admissions', ['is_deleted'], unique=False)
    op.create_table('college_modules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('module_name', sa.String(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('student_visible', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('visible_to_roles', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('\'["student"]\''), nullable=False),
    sa.Column('enabled_by', sa.String(), nullable=True),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['enabled_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('college_id', 'module_name', name='uq_college_module')
    )
    op.create_index(op.f('ix_college_modules_college_id'), 'college_modules', ['college_id'], unique=False)
    op.create_index(op.f('ix_college_modules_id'), 'college_modules', ['id'], unique=False)
    op.create_index(op.f('ix_college_modules_is_deleted'), 'college_modules', ['is_deleted'], unique=False)
    op.add_column('allocations', sa.Column('admission_id', sa.String(), nullable=True))
    op.alter_column('allocations', 'student_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index('ix_alloc_admission_year', 'allocations', ['admission_id', 'academic_year'], unique=False)
    op.create_foreign_key(None, 'allocations', 'admissions', ['admission_id'], ['id'], ondelete='CASCADE')
    op.create_check_constraint('ck_allocation_has_owner', 'allocations', 'student_id IS NOT NULL OR admission_id IS NOT NULL')
    op.create_check_constraint('ck_allocation_single_owner', 'allocations', 'NOT (student_id IS NOT NULL AND admission_id IS NOT NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_allocation_has_owner', 'allocations', type_='check')
    op.drop_constraint('ck_allocation_single_owner', 'allocations', type_='check')
    op.drop_constraint(None, 'allocations', type_='foreignkey')
    op.drop_index('ix_alloc_admission_year', table_name='allocations')
    op.alter_column('allocations', 'student_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('allocations', 'admission_id')
    op.drop_index(op.f('ix_college_modules_is_deleted'), table_name='college_modules')
    op.drop_index(op.f('ix_college_modules_id'), table_name='college_modules')
    op.drop_index(op.f('ix_college_modules_college_id'), table_name='college_modules')
    op.drop_table('college_modules')
    op.drop_index(op.f('ix_admissions_is_deleted'), table_name='admissions')
    op.drop_index('ix_admission_mobile', table_name='admissions')
    op.drop_table('admissions')
    # ### end Alembic commands ###
