"""Add ActivityPermission full schema

Revision ID: b5f5c86d99da
Revises: eb44ad8be8c6
Create Date: 2026-04-07 17:40:41.474185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b5f5c86d99da'
down_revision: Union[str, Sequence[str], None] = 'eb44ad8be8c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_permissions', sa.Column('department_id', sa.String(), nullable=False))
    op.add_column('activity_permissions', sa.Column('event_title', sa.String(), nullable=False))
    op.add_column('activity_permissions', sa.Column('event_date', sa.Date(), nullable=False))
    op.add_column('activity_permissions', sa.Column('event_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('activity_permissions', sa.Column('hod_permission_decision', sa.String(), nullable=True))
    op.add_column('activity_permissions', sa.Column('hod_permission_notes', sa.String(), nullable=True))
    op.add_column('activity_permissions', sa.Column('hod_permission_decided_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('activity_permissions', sa.Column('hod_report_decision', sa.String(), nullable=True))
    op.add_column('activity_permissions', sa.Column('hod_report_notes', sa.String(), nullable=True))
    op.add_column('activity_permissions', sa.Column('hod_report_decided_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('activity_permissions', sa.Column('principal_noted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('activity_permissions', sa.Column('principal_notes', sa.String(), nullable=True))
    op.add_column('activity_permissions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_activity_permissions_department_id'), 'activity_permissions', ['department_id'], unique=False)
    op.drop_constraint(op.f('activity_permissions_hod_approved_by_fkey'), 'activity_permissions', type_='foreignkey')
    op.create_foreign_key(None, 'activity_permissions', 'departments', ['department_id'], ['id'], ondelete='CASCADE')
    op.drop_column('activity_permissions', 'status')
    op.drop_column('activity_permissions', 'title')
    op.drop_column('activity_permissions', 'venue')
    op.drop_column('activity_permissions', 'hod_approved_by')
    op.drop_column('activity_permissions', 'description')
    op.drop_column('activity_permissions', 'date')
    op.drop_column('activity_permissions', 'report_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_permissions', sa.Column('report_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('activity_permissions', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('activity_permissions', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('activity_permissions', sa.Column('hod_approved_by', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('activity_permissions', sa.Column('venue', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('activity_permissions', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('activity_permissions', sa.Column('status', sa.VARCHAR(), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'activity_permissions', type_='foreignkey')
    op.create_foreign_key(op.f('activity_permissions_hod_approved_by_fkey'), 'activity_permissions', 'users', ['hod_approved_by'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_activity_permissions_department_id'), table_name='activity_permissions')
    op.drop_column('activity_permissions', 'created_at')
    op.drop_column('activity_permissions', 'principal_notes')
    op.drop_column('activity_permissions', 'principal_noted_at')
    op.drop_column('activity_permissions', 'hod_report_decided_at')
    op.drop_column('activity_permissions', 'hod_report_notes')
    op.drop_column('activity_permissions', 'hod_report_decision')
    op.drop_column('activity_permissions', 'hod_permission_decided_at')
    op.drop_column('activity_permissions', 'hod_permission_notes')
    op.drop_column('activity_permissions', 'hod_permission_decision')
    op.drop_column('activity_permissions', 'event_details')
    op.drop_column('activity_permissions', 'event_date')
    op.drop_column('activity_permissions', 'event_title')
    op.drop_column('activity_permissions', 'department_id')
    # ### end Alembic commands ###
