"""Add outcomes and assessments tables

Revision ID: c50b0cb57389
Revises: 6ca586af80a7
Create Date: 2026-04-20 23:41:02.631693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c50b0cb57389'
down_revision: Union[str, Sequence[str], None] = '6ca586af80a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('program_outcomes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('department_id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_id', 'code', name='uq_department_po_code')
    )
    op.create_index(op.f('ix_program_outcomes_id'), 'program_outcomes', ['id'], unique=False)
    op.create_index(op.f('ix_program_outcomes_is_deleted'), 'program_outcomes', ['is_deleted'], unique=False)
    op.create_table('course_outcomes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('course_id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('bloom_level', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'code', name='uq_course_co_code')
    )
    op.create_index(op.f('ix_course_outcomes_id'), 'course_outcomes', ['id'], unique=False)
    op.create_index(op.f('ix_course_outcomes_is_deleted'), 'course_outcomes', ['is_deleted'], unique=False)
    op.create_table('co_po_mappings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('co_id', sa.String(), nullable=False),
    sa.Column('po_id', sa.String(), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['co_id'], ['course_outcomes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['po_id'], ['program_outcomes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('co_id', 'po_id', name='uq_co_po_mapping')
    )
    op.create_index(op.f('ix_co_po_mappings_id'), 'co_po_mappings', ['id'], unique=False)
    op.create_index(op.f('ix_co_po_mappings_is_deleted'), 'co_po_mappings', ['is_deleted'], unique=False)
    op.alter_column('ai_generated_assessments', 'prompt_used',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.drop_index(op.f('ix_ai_generated_assessments_course_id'), table_name='ai_generated_assessments')
    op.drop_index(op.f('ix_ai_generated_assessments_faculty_id'), table_name='ai_generated_assessments')
    op.drop_column('ai_generated_assessments', 'generated_content')
    op.drop_column('ai_generated_assessments', 'co_po_mapping')
    op.add_column('assessment_questions', sa.Column('co_id', sa.String(), nullable=True))
    op.add_column('assessment_questions', sa.Column('po_id', sa.String(), nullable=True))
    op.add_column('assessment_questions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('assessment_questions', 'question_text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('assessment_questions', 'marks',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('assessment_questions', 'answer_key',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('ix_assessment_questions_assessment_id'), table_name='assessment_questions')
    op.create_foreign_key(None, 'assessment_questions', 'course_outcomes', ['co_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'assessment_questions', 'program_outcomes', ['po_id'], ['id'], ondelete='SET NULL')
    op.drop_column('assessment_questions', 'co_mapped')
    op.drop_column('assessment_questions', 'po_mapped')
    op.drop_column('courses', 'course_outcomes')
    op.drop_column('departments', 'program_outcomes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('program_outcomes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('courses', sa.Column('course_outcomes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('assessment_questions', sa.Column('po_mapped', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('assessment_questions', sa.Column('co_mapped', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'assessment_questions', type_='foreignkey')
    op.drop_constraint(None, 'assessment_questions', type_='foreignkey')
    op.create_index(op.f('ix_assessment_questions_assessment_id'), 'assessment_questions', ['assessment_id'], unique=False)
    op.alter_column('assessment_questions', 'answer_key',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('assessment_questions', 'marks',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('assessment_questions', 'question_text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('assessment_questions', 'created_at')
    op.drop_column('assessment_questions', 'po_id')
    op.drop_column('assessment_questions', 'co_id')
    op.add_column('ai_generated_assessments', sa.Column('co_po_mapping', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('ai_generated_assessments', sa.Column('generated_content', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_ai_generated_assessments_faculty_id'), 'ai_generated_assessments', ['faculty_id'], unique=False)
    op.create_index(op.f('ix_ai_generated_assessments_course_id'), 'ai_generated_assessments', ['course_id'], unique=False)
    op.alter_column('ai_generated_assessments', 'prompt_used',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.drop_index(op.f('ix_co_po_mappings_is_deleted'), table_name='co_po_mappings')
    op.drop_index(op.f('ix_co_po_mappings_id'), table_name='co_po_mappings')
    op.drop_table('co_po_mappings')
    op.drop_index(op.f('ix_course_outcomes_is_deleted'), table_name='course_outcomes')
    op.drop_index(op.f('ix_course_outcomes_id'), table_name='course_outcomes')
    op.drop_table('course_outcomes')
    op.drop_index(op.f('ix_program_outcomes_is_deleted'), table_name='program_outcomes')
    op.drop_index(op.f('ix_program_outcomes_id'), table_name='program_outcomes')
    op.drop_table('program_outcomes')
    # ### end Alembic commands ###
