"""hod_dashboard_phase2_cancellation_meta

Revision ID: d446512ce44f
Revises: 83deaee2758a
Create Date: 2026-04-06 19:13:54.573626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd446512ce44f'
down_revision: Union[str, Sequence[str], None] = '83deaee2758a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leave_requests', sa.Column('cancellation_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leave_requests', 'cancellation_meta')
    # ### end Alembic commands ###
