"""add pinned_insights

Revision ID: e3cbdf360837
Revises: a57dc0ec4125
Create Date: 2026-04-17 03:14:22.960375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3cbdf360837'
down_revision: Union[str, Sequence[str], None] = 'a57dc0ec4125'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pinned_insights',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('nl_query', sa.Text(), nullable=False),
    sa.Column('cached_sql', sa.Text(), nullable=False),
    sa.Column('chart_suggestion', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pinned_insights_college_id'), 'pinned_insights', ['college_id'], unique=False)
    op.create_index(op.f('ix_pinned_insights_id'), 'pinned_insights', ['id'], unique=False)
    op.create_index(op.f('ix_pinned_insights_is_deleted'), 'pinned_insights', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_pinned_insights_user_id'), 'pinned_insights', ['user_id'], unique=False)
    op.drop_index(op.f('ix_mark_entries_student_id'), table_name='mark_submission_entries')
    op.drop_index(op.f('ix_mark_entries_sub_student'), table_name='mark_submission_entries')
    op.drop_index(op.f('ix_semester_grades_college_student'), table_name='semester_grades')
    op.drop_index(op.f('ix_semester_grades_student'), table_name='semester_grades')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_semester_grades_student'), 'semester_grades', ['student_id'], unique=False)
    op.create_index(op.f('ix_semester_grades_college_student'), 'semester_grades', ['college_id', 'student_id', 'semester'], unique=False)
    op.create_index(op.f('ix_mark_entries_sub_student'), 'mark_submission_entries', ['submission_id', 'student_id'], unique=False)
    op.create_index(op.f('ix_mark_entries_student_id'), 'mark_submission_entries', ['student_id'], unique=False)
    op.drop_index(op.f('ix_pinned_insights_user_id'), table_name='pinned_insights')
    op.drop_index(op.f('ix_pinned_insights_is_deleted'), table_name='pinned_insights')
    op.drop_index(op.f('ix_pinned_insights_id'), table_name='pinned_insights')
    op.drop_index(op.f('ix_pinned_insights_college_id'), table_name='pinned_insights')
    op.drop_table('pinned_insights')
    # ### end Alembic commands ###
