"""Phase4 course registration and hall tickets

Revision ID: e779d01f158a
Revises: 6531ec5c9ce8
Create Date: 2026-04-06 10:54:48.427108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e779d01f158a'
down_revision: Union[str, Sequence[str], None] = '6531ec5c9ce8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_registrations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('subject_code', sa.String(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('is_arrear', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('status', sa.String(), server_default='registered', nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'subject_code', 'academic_year', name='uq_course_reg')
    )
    op.create_index('ix_course_reg_college_status', 'course_registrations', ['college_id', 'status'], unique=False)
    op.create_index('ix_course_reg_student_semester', 'course_registrations', ['student_id', 'academic_year', 'semester'], unique=False)
    op.create_index(op.f('ix_course_registrations_id'), 'course_registrations', ['id'], unique=False)
    op.create_index(op.f('ix_course_registrations_is_deleted'), 'course_registrations', ['is_deleted'], unique=False)
    op.create_table('registration_windows',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('open_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('close_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reg_window_college_status', 'registration_windows', ['college_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_registration_windows_id'), 'registration_windows', ['id'], unique=False)
    op.create_index(op.f('ix_registration_windows_is_deleted'), 'registration_windows', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registration_windows_is_deleted'), table_name='registration_windows')
    op.drop_index(op.f('ix_registration_windows_id'), table_name='registration_windows')
    op.drop_index('ix_reg_window_college_status', table_name='registration_windows')
    op.drop_table('registration_windows')
    op.drop_index(op.f('ix_course_registrations_is_deleted'), table_name='course_registrations')
    op.drop_index(op.f('ix_course_registrations_id'), table_name='course_registrations')
    op.drop_index('ix_course_reg_student_semester', table_name='course_registrations')
    op.drop_index('ix_course_reg_college_status', table_name='course_registrations')
    op.drop_table('course_registrations')
    # ### end Alembic commands ###
