"""Phase5 NAAC Institutional Data

Revision ID: e80419ea537f
Revises: e779d01f158a
Create Date: 2026-04-06 10:59:28.898975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e80419ea537f'
down_revision: Union[str, Sequence[str], None] = 'e779d01f158a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institution_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('recognitions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('infrastructure', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('library', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mous', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extension_activities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('research_publications', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('college_id')
    )
    op.create_index(op.f('ix_institution_profiles_id'), 'institution_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_institution_profiles_is_deleted'), 'institution_profiles', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_institution_profiles_is_deleted'), table_name='institution_profiles')
    op.drop_index(op.f('ix_institution_profiles_id'), table_name='institution_profiles')
    op.drop_table('institution_profiles')
    # ### end Alembic commands ###
